# Semantic Space Calibration Experiments Using CLIP

This notebook demonstrates geometric calibration using CLIP's semantic embeddings from Hugging Face's transformers library instead of raw pixel space.

In [1]:
# Standard imports
import os
import logging
import numpy as np
import torch
import pandas as pd
from tqdm import tqdm

# Project imports
from utils.logging_config import setup_logging
from utils.model_utils import train_or_load_model
from utils.data_utils import load_and_split_data
from utils.utils import SemanticCompression
from calibrators.geometric_calibrators import GeometricCalibrator
from utils.metrics import CalibrationMetrics

# Initialize logging
setup_logging()
logger = logging.getLogger(__name__)

# Check for GPU availability
device = "cuda" if torch.cuda.is_available() else "cpu"
logger.info(f"Using device: {device}")

2025-02-14 00:20:05.060868: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-14 00:20:07.466625: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2025-02-14 00:20:13,365 - INFO - Loading faiss with AVX2 support.
2025-02-14 00:20:13,492 - INFO - Successfully loaded faiss with AVX2 support.
2025-02-14 00:20:21,820 - INFO - Using device: cpu

In [2]:
def prepare_data_semantic(dataset_name, random_state):
    """Load and prepare data with semantic embeddings."""
    # Load raw data
    X_train, X_val, X_test, y_train, y_val, y_test = load_and_split_data(
        dataset_name, 
        random_state
    )
    
    # Initialize semantic compression with CLIP
    semantic_compressor = SemanticCompression(model_name="openai/clip-vit-base-patch32")
    
    # Process each dataset split
    logger.info("Converting datasets to semantic embeddings...")
    
    X_train_semantic, _ = semantic_compressor(X_train, y_train)
    logger.info(f"Training embeddings shape: {X_train_semantic.shape}")
    
    X_val_semantic, _ = semantic_compressor(X_val, y_val)
    logger.info(f"Validation embeddings shape: {X_val_semantic.shape}")
    
    X_test_semantic, _ = semantic_compressor(X_test, y_test)
    logger.info(f"Test embeddings shape: {X_test_semantic.shape}")
    
    return (
        X_train_semantic, X_val_semantic, X_test_semantic,
        y_train, y_val, y_test
    )

In [3]:
from utils.utils import Compression, StabilitySpace

def run_semantic_calibration_experiment(dataset_name, model_type="cnn", random_state=2, 
                                        compression_type="semantic", compression_param="mobilenet"):
    """
    Run calibration experiment using semantic compression within StabilitySpace.
    Handles both CNN and sklearn models properly by ensuring correct data shapes.

    Parameters:
        dataset_name (str): Name of the dataset (e.g., CIFAR10).
        model_type (str): Type of model (default is "cnn").
        random_state (int): Random seed for reproducibility.
        compression_type (str): Compression method (e.g., 'semantic', 'PCA', 'Avgpool', 'Maxpool').
        compression_param (str/int): Parameter for compression (e.g., 'mobilenet' for semantic, 2 for pooling).

    Returns:
        pd.DataFrame: A dataframe containing calibration metrics.
    """
    try:
        print("\n=== Starting Semantic Calibration Experiment ===")
        print(f"Dataset: {dataset_name}")
        print(f"Model type: {model_type}")
        print(f"Compression type: {compression_type}, Parameter: {compression_param}")

        # Load original data
        logger.info("Loading original data for model training...")
        X_train, X_val, X_test, y_train, y_val, y_test = load_and_split_data(dataset_name, random_state)

        print(f"\nData shapes after loading:")
        print(f"X_train: {X_train.shape}")
        print(f"X_val: {X_val.shape}")
        print(f"X_test: {X_test.shape}")

        # For sklearn models, reshape data before training
        if model_type not in ["cnn", "densenet", "pretrained_resnet"]:
            logger.info(f"Reshaping data for {model_type} model...")
            X_train_model = X_train.reshape(X_train.shape[0], -1)
            X_val_model = X_val.reshape(X_val.shape[0], -1)
            X_test_model = X_test.reshape(X_test.shape[0], -1)
        else:
            X_train_model = X_train
            X_val_model = X_val
            X_test_model = X_test

        # Train model on reshaped data
        logger.info(f"Training {model_type} model...")
        model = train_or_load_model(
            X_train_model, y_train,
            X_val_model, y_val,
            dataset_name=dataset_name,
            random_state=random_state,
            model_type=model_type
        )

        # Get predictions using properly shaped data
        logger.info("Getting model predictions...")
        if model_type in ["cnn", "densenet", "pretrained_resnet"]:
            features_test = model.predict(X_test_model)
            y_test_pred = np.argmax(features_test, axis=1)
        else:
            features_test = model.predict_proba(X_test_model)
            y_test_pred = model.predict(X_test_model)

        # Create compression configuration dynamically
        compression = Compression(
            compression_types=[compression_type],
            compression_params=[compression_param]
        )

        # Run calibration methods
        calibrations = {
            "faiss_exact": {"library": "faiss", "mode": "exact"},
            "fast_separation": {"library": "fast_separation", "mode": None},
        }

        results = []
        for name, config in calibrations.items():
            logger.info(f"Running {name} calibration with {compression_type} compression...")
            print(f"\n=== Starting {name} calibration ===")
            print(f"Configuration: {config}")

            try:
                # Create StabilitySpace with selected compression
                stability_space = StabilitySpace(
                    X_train=X_train,  
                    y_train=y_train,
                    compression=compression,
                    library=config["library"],
                    metric="cosine"
                )

                # Initialize calibrator with stability space
                calibrator = GeometricCalibrator(
                    model=model,
                    X_train=X_train_model,  
                    y_train=y_train,
                    stability_space=stability_space,
                    library=config["library"],
                    metric="cosine"
                )

                # Fit and calibrate
                calibrator.fit(X_val_model, y_val)  # Use properly shaped validation data
                calibrated_probs = calibrator.calibrate(X_test_model)  # Use properly shaped test data

                # Calculate metrics
                metrics = CalibrationMetrics(
                    calibrated_probs,
                    y_test_pred,
                    y_test,
                    n_bins=20
                )

                results.append({
                    "Method": f"{compression_type}_{name}",
                    **metrics.calculate_all_metrics()
                })

            except Exception as e:
                logger.error(f"Error in {name} calibration: {str(e)}")
                continue

        return pd.DataFrame(results)

    except Exception as e:
        logger.error(f"Error in experiment: {str(e)}")
        raise

In [4]:
import os
import logging

def run_experiments(
    datasets=["CIFAR10", "MNIST"],
    models=["RF", "GB", "cnn"],
    random_states=[42],  # List of random states to try
    compression_types=["semantic"],  # List of compression types
    compression_params={"semantic": "mobilenet"}  # Mapping of compression type to its parameters
):
    """
    Run calibration experiments for all dataset-model combinations, allowing multiple random states and compression methods.
    
    Parameters:
        datasets (list): List of dataset names to run experiments on.
        models (list): List of model types to use.
        random_states (list): List of random seed values for reproducibility.
        compression_types (list): List of compression methods to test.
        compression_params (dict): Dictionary mapping compression types to their parameters.
    """
    logger = logging.getLogger(__name__)
    
    for dataset in datasets:
        print(f"\nRunning semantic space calibration experiments for {dataset}")
        
        # Create base output directory for this dataset
        base_output_dir = f"output/semantic_calibration/{dataset}"
        os.makedirs(base_output_dir, exist_ok=True)
        
        for model_type in models:
            for random_state in random_states:
                for compression_type in compression_types:
                    compression_param = compression_params.get(compression_type, None)  # Get corresponding parameter
                    
                    try:
                        logger.info(f"Processing {dataset} with {model_type}, random_state={random_state}, "
                                    f"compression={compression_type}, param={compression_param}")
                        
                        # Run experiment with specified parameters
                        results_df = run_semantic_calibration_experiment(
                            dataset_name=dataset,
                            model_type=model_type,
                            random_state=random_state,
                            compression_type=compression_type,
                            compression_param=compression_param
                        )
                        
                        # Save results
                        model_output_dir = os.path.join(base_output_dir, model_type, f"rs_{random_state}", compression_type)
                        os.makedirs(model_output_dir, exist_ok=True)
                        results_file = os.path.join(model_output_dir, "results.csv")
                        
                        results_df.to_csv(results_file, index=False)
                        logger.info(f"Results saved to {results_file}")
                        
                        # Display results
                        display(results_df)
                    
                    except Exception as e:
                        logger.error(f"Error processing {dataset} with {model_type}, random_state={random_state}, "
                                     f"compression={compression_type}: {str(e)}")
                        continue


def prepare_data_semantic(dataset_name, random_state, model_type="mobilenet"):
    """
    Load and prepare data with semantic embeddings using specified model.
    
    Parameters:
        dataset_name (str): Name of the dataset to load
        random_state (int): Random seed for reproducibility
        model_type (str): Type of semantic model to use ('clip', 'efficientnet', or 'mobilenet')
    
    Returns:
        tuple: Processed data splits (X_train, X_val, X_test, y_train, y_val, y_test)
    """
    # Load raw data
    X_train, X_val, X_test, y_train, y_val, y_test = load_and_split_data(
        dataset_name, 
        random_state
    )
    
    # Initialize semantic compression with appropriate model
    model_configs = {
        'clip': "openai/clip-vit-base-patch32",
        'efficientnet': "tf_efficientnet_lite0",
        'mobilenet': "mobilenetv3_small_100"
    }
    
    logger.info(f"Initializing semantic compression with {model_type} model")
    semantic_compressor = SemanticCompression(
        model_type=model_type,
        model_name=model_configs.get(model_type)
    )
    
    # Process each dataset split with progress tracking
    logger.info(f"Converting datasets to {model_type} embeddings...")
    
    X_train_semantic, _ = semantic_compressor(X_train, y_train)
    logger.info(f"Training embeddings shape: {X_train_semantic.shape}")
    
    X_val_semantic, _ = semantic_compressor(X_val, y_val)
    logger.info(f"Validation embeddings shape: {X_val_semantic.shape}")
    
    X_test_semantic, _ = semantic_compressor(X_test, y_test)
    logger.info(f"Test embeddings shape: {X_test_semantic.shape}")
    
    return (
        X_train_semantic, X_val_semantic, X_test_semantic,
        y_train, y_val, y_test
    )

# Function to run all semantic model experiments
def run_all_semantic_experiments(
    datasets=["CIFAR10", "MNIST"],
    models=["RF", "GB", "cnn"],
    random_states=[2, 42, 100],
    semantic_models=["efficientnet", "clip", "mobilenet"]
):
    """
    Run experiments for all combinations of semantic models and collect results.
    
    Parameters:
        datasets (list): List of datasets to evaluate
        models (list): List of ML models to test
        random_states (list): Random seeds for reproducibility
        semantic_models (list): List of semantic models to compare
    """
    # Create summary directory for combined results
    summary_dir = "output/semantic_comparison"
    os.makedirs(summary_dir, exist_ok=True)
    
    # Store results for each semantic model
    all_results = []
    
    for semantic_model in semantic_models:
        logger.info(f"\nRunning experiments with {semantic_model} embeddings")
        
        # Run experiments for current semantic model
        run_experiments(
            datasets=datasets,
            models=models,
            random_states=random_states,
            compression_types=["semantic"],
            compression_params={"semantic": semantic_model}
        )
        
        # Collect results from all experiments for this semantic model
        model_results = []
        for dataset in datasets:
            for model in models:
                for rs in random_states:
                    results_path = f"output/semantic_calibration/{dataset}/{model}/rs_{rs}/semantic/results.csv"
                    if os.path.exists(results_path):
                        df = pd.read_csv(results_path)
                        df['Semantic_Model'] = semantic_model
                        df['Dataset'] = dataset
                        df['Model'] = model
                        df['Random_State'] = rs
                        model_results.append(df)
        
        all_results.extend(model_results)
    
    # Combine all results and generate comparison
    if all_results:
        combined_df = pd.concat(all_results, ignore_index=True)
        
        # Save combined results
        combined_df.to_csv(f"{summary_dir}/all_semantic_models_comparison.csv", index=False)
        
        # Generate summary statistics
        summary = combined_df.groupby(['Semantic_Model', 'Dataset', 'Model']).agg({
            'ECE': ['mean', 'std'],
            'MCE': ['mean', 'std']
        }).round(4)
        
        summary.to_csv(f"{summary_dir}/semantic_models_summary.csv")
        logger.info(f"Comparison results saved to {summary_dir}")
        
        # Display summary
        display(summary)

In [ ]:
# # Run all experiments with automatic comparison
run_all_semantic_experiments(
    datasets=["CIFAR10", "MNIST"],
    models=["RF", "GB", "cnn"],
    random_states=[2, 42, 100],
    semantic_models=["mobilenet", "clip", "efficientnet"]
)

2025-02-14 00:20:53,678 - INFO -
Running experiments with mobilenet embeddings
2025-02-14 00:20:53,682 - INFO - Processing CIFAR10 with RF, random_state=2, compression=semantic, param=mobilenet
2025-02-14 00:20:53,683 - INFO - Loading original data for model training...
2025-02-14 00:20:53,683 - INFO - Loading dataset: CIFAR10

Running semantic space calibration experiments for CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: RF
Compression type: semantic, Parameter: mobilenet
Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 9s 0us/step

2025-02-14 00:21:07,951 - INFO - Combining and splitting data
2025-02-14 00:21:08,248 - INFO - Data normalization completed
2025-02-14 00:21:08,252 - INFO - Reshaping data for RF model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 00:21:08,902 - INFO - Training RF model...
2025-02-14 00:21:08,910 - INFO - Training new RF model.
2025-02-14 00:21:08,911 - INFO - Model type RF
2025-02-14 00:27:10,947 - INFO - Model saved at output/CIFAR10/2/saved_models/RF_model.keras.
2025-02-14 00:27:10,949 - INFO - Getting model predictions...
2025-02-14 00:27:14,539 - INFO -
=== Compression Initialization ===
2025-02-14 00:27:14,540 - INFO - Original compression_types: ['semantic']
2025-02-14 00:27:14,540 - INFO - Original compression_params: ['mobilenet']
2025-02-14 00:27:14,541 - INFO - Final compression_types: ['semantic']
2025-02-14 00:27:14,541 - INFO - Final compression_params: ['mobilenet']
2025-02-14 00:27:14,541 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 00:27:14,628 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)

model.safetensors:   0%|          | 0.00/10.2M [00:00<?, ?B/s]

2025-02-14 00:27:15,942 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 00:27:16,011 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 00:27:16,300 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 00:27:16,302 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 00:27:16,304 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 00:27:16,306 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 00:27:16,316 - INFO - Applying compression to training data.
2025-02-14 00:27:16,321 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 00:27:16,323 - INFO - Input dimensionality check:
2025-02-14 00:27:16,325 - INFO - - Number of dimensions: 4
2025-02-14 00:27:16,327 - INFO -
=== Compression Call ===
2025-02-14 00:27:16,330 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 00:27:16,331 - INFO - Input dtype: float32
2025-02-14 00:27:16,333 - INFO - Train mode: True
2025-02-14 00:27:16,336 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 00:27:16,337 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 00:27:16,339 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:27:16,341 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:19<00:00, 14.16it/s]
2025-02-14 00:27:36,308 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 00:27:36,309 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 00:27:36,310 - INFO - After semantic compression:
2025-02-14 00:27:36,311 - INFO - - Output shape: (36000, 256)
2025-02-14 00:27:36,311 - INFO - - Output dtype: float32
2025-02-14 00:27:36,312 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 00:27:36,551 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 00:27:36,552 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 00:27:36,552 - INFO - Compression mode: None
2025-02-14 00:27:36,553 - INFO - Compression param: None
2025-02-14 00:27:36,553 - INFO - Library: faiss
2025-02-14 00:27:36,553 - INFO - Metric: cosine
2025-02-14 00:27:36,554 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 00:27:36,555 - INFO - Number of unique labels: 10
2025-02-14 00:27:36,555 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 00:27:36,556 - INFO - Initialized GeometricCalibrator with model RandomForestClassifier and fitting function IsotonicRegression.
2025-02-14 00:27:36,556 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 00:27:36,557 - INFO - Sklearn model detected
2025-02-14 00:27:39,426 - INFO - Applying compression before stability calculation
2025-02-14 00:27:39,427 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:27:39,428 - INFO - Input dimensionality check:
2025-02-14 00:27:39,428 - INFO - - Number of dimensions: 2
2025-02-14 00:27:39,429 - INFO -
=== Compression Call ===
2025-02-14 00:27:39,429 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:27:39,430 - INFO - Input dtype: float32
2025-02-14 00:27:39,431 - INFO - Train mode: False
2025-02-14 00:27:39,432 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:27:39,432 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:27:39,433 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:27:39,433 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:27:39,434 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 15.91it/s]
2025-02-14 00:27:45,354 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:27:45,356 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:27:45,356 - INFO - After semantic compression:
2025-02-14 00:27:45,357 - INFO - - Output shape: (12000, 256)
2025-02-14 00:27:45,357 - INFO - - Output dtype: float32
2025-02-14 00:27:45,358 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:27:45,359 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:29<00:00, 403.20sample/s]
2025-02-14 00:28:15,126 - INFO - Time taken for stability calculation: 35.70 seconds
2025-02-14 00:28:15,127 - INFO - Stability values (first 5): [-2670.  -8736.  -2809.5   178.5 -3920.5]
2025-02-14 00:28:15,275 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 00:28:15,275 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 00:28:17,956 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 00:28:17,957 - INFO - Applying compression before stability calculation
2025-02-14 00:28:17,957 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:28:17,958 - INFO - Input dimensionality check:
2025-02-14 00:28:17,958 - INFO - - Number of dimensions: 2
2025-02-14 00:28:17,958 - INFO -
=== Compression Call ===
2025-02-14 00:28:17,959 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:28:17,959 - INFO - Input dtype: float32
2025-02-14 00:28:17,959 - INFO - Train mode: False
2025-02-14 00:28:17,960 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:28:17,960 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:28:17,960 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:28:17,961 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:28:17,961 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 16.00it/s]
2025-02-14 00:28:23,847 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:28:23,848 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:28:23,848 - INFO - After semantic compression:
2025-02-14 00:28:23,849 - INFO - - Output shape: (12000, 256)
2025-02-14 00:28:23,849 - INFO - - Output dtype: float32
2025-02-14 00:28:23,850 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:28:23,850 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:30<00:00, 398.87sample/s]
2025-02-14 00:28:53,940 - INFO - Time taken for stability calculation: 35.98 seconds
2025-02-14 00:28:53,941 - INFO - Stability values during calibration (first 10): [ -8025.   -9927.   -1919.   -7257.5   -518.5  -8643.     320.  -11876.
   -733.5  -2579. ]
2025-02-14 00:28:53,943 - INFO - Calibrated values (first 10): [0.46763122 0.46763122 0.47125803 0.46763122 0.47125803 0.46763122
 0.48353208 0.46763122 0.47125803 0.47125803]
2025-02-14 00:28:54,174 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 00:28:54,174 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 00:28:54,177 - INFO - Final ECE value: 0.0022208734054260854
2025-02-14 00:28:54,177 - INFO - Calculating Maximum Calibration Error.
2025-02-14 00:28:54,179 - INFO - Final MCE value: 0.5555555555555555
2025-02-14 00:28:54,180 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 00:28:54,180 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 00:28:54,183 - INFO - Applying compression to training data.
2025-02-14 00:28:54,183 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 00:28:54,184 - INFO - Input dimensionality check:
2025-02-14 00:28:54,184 - INFO - - Number of dimensions: 4
2025-02-14 00:28:54,184 - INFO -
=== Compression Call ===
2025-02-14 00:28:54,185 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 00:28:54,185 - INFO - Input dtype: float32
2025-02-14 00:28:54,185 - INFO - Train mode: True
2025-02-14 00:28:54,186 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 00:28:54,186 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 00:28:54,186 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:28:54,187 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 18.56it/s]
2025-02-14 00:29:09,418 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 00:29:09,419 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 00:29:09,420 - INFO - After semantic compression:
2025-02-14 00:29:09,421 - INFO - - Output shape: (36000, 256)
2025-02-14 00:29:09,421 - INFO - - Output dtype: float32
2025-02-14 00:29:09,422 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 00:29:09,557 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 00:29:09,558 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 00:29:09,559 - INFO - Compression mode: None
2025-02-14 00:29:09,560 - INFO - Compression param: None
2025-02-14 00:29:09,560 - INFO - Library: fast_separation
2025-02-14 00:29:09,561 - INFO - Metric: cosine
2025-02-14 00:29:09,562 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 00:29:09,563 - INFO - Number of unique labels: 10
2025-02-14 00:29:09,564 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 00:29:09,564 - INFO - Initialized GeometricCalibrator with model RandomForestClassifier and fitting function IsotonicRegression.
2025-02-14 00:29:09,568 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 00:29:09,569 - INFO - Sklearn model detected
2025-02-14 00:29:12,265 - INFO - Applying compression before stability calculation
2025-02-14 00:29:12,265 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:29:12,266 - INFO - Input dimensionality check:
2025-02-14 00:29:12,267 - INFO - - Number of dimensions: 2
2025-02-14 00:29:12,267 - INFO -
=== Compression Call ===
2025-02-14 00:29:12,268 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:29:12,269 - INFO - Input dtype: float32
2025-02-14 00:29:12,269 - INFO - Train mode: False
2025-02-14 00:29:12,270 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:29:12,270 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:29:12,271 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:29:12,272 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:29:12,272 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.36it/s]
2025-02-14 00:29:17,142 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:29:17,142 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:29:17,143 - INFO - After semantic compression:
2025-02-14 00:29:17,144 - INFO - - Output shape: (12000, 256)
2025-02-14 00:29:17,145 - INFO - - Output dtype: float32
2025-02-14 00:29:17,146 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:29:17,147 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [03:56<00:00, 50.82sample/s]
2025-02-14 00:33:13,266 - INFO - Time taken for stability calculation: 241.00 seconds
2025-02-14 00:33:13,266 - INFO - Stability values (first 5): [-0.01058957 -0.01373553  0.0070222  -0.00326452 -0.00366169]
2025-02-14 00:33:13,437 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 00:33:13,437 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 00:33:16,113 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 00:33:16,114 - INFO - Applying compression before stability calculation
2025-02-14 00:33:16,114 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:33:16,115 - INFO - Input dimensionality check:
2025-02-14 00:33:16,115 - INFO - - Number of dimensions: 2
2025-02-14 00:33:16,116 - INFO -
=== Compression Call ===
2025-02-14 00:33:16,117 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:33:16,117 - INFO - Input dtype: float32
2025-02-14 00:33:16,118 - INFO - Train mode: False
2025-02-14 00:33:16,118 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:33:16,118 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:33:16,119 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:33:16,119 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:33:16,120 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.05it/s]
2025-02-14 00:33:21,069 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:33:21,070 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:33:21,071 - INFO - After semantic compression:
2025-02-14 00:33:21,072 - INFO - - Output shape: (12000, 256)
2025-02-14 00:33:21,073 - INFO - - Output dtype: float32
2025-02-14 00:33:21,074 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:33:21,075 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [03:51<00:00, 51.78sample/s]
2025-02-14 00:37:12,813 - INFO - Time taken for stability calculation: 236.70 seconds
2025-02-14 00:37:12,813 - INFO - Stability values during calibration (first 10): [ 0.01478919  0.00196478 -0.01405135 -0.00253999 -0.02024296 -0.00906578
 -0.00370094  0.00161016 -0.02442393 -0.0006167 ]
2025-02-14 00:37:12,815 - INFO - Calibrated values (first 10): [0.84732824 0.62099125 0.32291667 0.51128122 0.22844828 0.40229885
 0.51128122 0.62099125 0.18939394 0.59782609]
2025-02-14 00:37:13,043 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 00:37:13,043 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 00:37:13,046 - INFO - Final ECE value: 0.021538959231699465
2025-02-14 00:37:13,046 - INFO - Calculating Maximum Calibration Error.
2025-02-14 00:37:13,049 - INFO - Final MCE value: 0.07396449704142027
2025-02-14 00:37:13,080 - INFO - Results saved to output/semantic_calibration/CIFAR10/RF/rs_2/semantic/results.csv

                     Method       ECE       MCE
0      semantic_faiss_exact  0.002221  0.555556
1  semantic_fast_separation  0.021539  0.073964

2025-02-14 00:37:13,093 - INFO - Processing CIFAR10 with RF, random_state=42, compression=semantic, param=mobilenet
2025-02-14 00:37:13,094 - INFO - Loading original data for model training...
2025-02-14 00:37:13,094 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: RF
Compression type: semantic, Parameter: mobilenet

2025-02-14 00:37:15,744 - INFO - Combining and splitting data
2025-02-14 00:37:16,028 - INFO - Data normalization completed
2025-02-14 00:37:16,032 - INFO - Reshaping data for RF model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 00:37:16,732 - INFO - Training RF model...
2025-02-14 00:37:16,740 - INFO - Training new RF model.
2025-02-14 00:37:16,741 - INFO - Model type RF
2025-02-14 00:43:21,516 - INFO - Model saved at output/CIFAR10/42/saved_models/RF_model.keras.
2025-02-14 00:43:21,517 - INFO - Getting model predictions...
2025-02-14 00:43:24,417 - INFO -
=== Compression Initialization ===
2025-02-14 00:43:24,418 - INFO - Original compression_types: ['semantic']
2025-02-14 00:43:24,419 - INFO - Original compression_params: ['mobilenet']
2025-02-14 00:43:24,419 - INFO - Final compression_types: ['semantic']
2025-02-14 00:43:24,420 - INFO - Final compression_params: ['mobilenet']
2025-02-14 00:43:24,421 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 00:43:24,464 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)
2025-02-14 00:43:24,907 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 00:43:24,929 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 00:43:24,960 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 00:43:24,961 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 00:43:24,962 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 00:43:24,963 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 00:43:24,969 - INFO - Applying compression to training data.
2025-02-14 00:43:24,970 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 00:43:24,971 - INFO - Input dimensionality check:
2025-02-14 00:43:24,971 - INFO - - Number of dimensions: 4
2025-02-14 00:43:24,972 - INFO -
=== Compression Call ===
2025-02-14 00:43:24,973 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 00:43:24,974 - INFO - Input dtype: float32
2025-02-14 00:43:24,975 - INFO - Train mode: True
2025-02-14 00:43:24,976 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 00:43:24,977 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 00:43:24,977 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:43:24,978 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:16<00:00, 17.09it/s]
2025-02-14 00:43:41,525 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 00:43:41,526 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 00:43:41,527 - INFO - After semantic compression:
2025-02-14 00:43:41,528 - INFO - - Output shape: (36000, 256)
2025-02-14 00:43:41,529 - INFO - - Output dtype: float32
2025-02-14 00:43:41,530 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 00:43:41,705 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 00:43:41,706 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 00:43:41,706 - INFO - Compression mode: None
2025-02-14 00:43:41,707 - INFO - Compression param: None
2025-02-14 00:43:41,708 - INFO - Library: faiss
2025-02-14 00:43:41,709 - INFO - Metric: cosine
2025-02-14 00:43:41,709 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 00:43:41,711 - INFO - Number of unique labels: 10
2025-02-14 00:43:41,712 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 00:43:41,713 - INFO - Initialized GeometricCalibrator with model RandomForestClassifier and fitting function IsotonicRegression.
2025-02-14 00:43:41,713 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 00:43:41,714 - INFO - Sklearn model detected
2025-02-14 00:43:45,738 - INFO - Applying compression before stability calculation
2025-02-14 00:43:45,739 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:43:45,739 - INFO - Input dimensionality check:
2025-02-14 00:43:45,740 - INFO - - Number of dimensions: 2
2025-02-14 00:43:45,741 - INFO -
=== Compression Call ===
2025-02-14 00:43:45,741 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:43:45,741 - INFO - Input dtype: float32
2025-02-14 00:43:45,742 - INFO - Train mode: False
2025-02-14 00:43:45,742 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:43:45,742 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:43:45,743 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:43:45,743 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:43:45,744 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 16.75it/s]
2025-02-14 00:43:51,377 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:43:51,378 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:43:51,379 - INFO - After semantic compression:
2025-02-14 00:43:51,387 - INFO - - Output shape: (12000, 256)
2025-02-14 00:43:51,388 - INFO - - Output dtype: float32
2025-02-14 00:43:51,388 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:43:51,389 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:31<00:00, 386.61sample/s]
2025-02-14 00:44:22,440 - INFO - Time taken for stability calculation: 36.70 seconds
2025-02-14 00:44:22,441 - INFO - Stability values (first 5): [   440.   -6601.5 -14125.   -7106.    -146.5]
2025-02-14 00:44:22,696 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 00:44:22,697 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 00:44:25,463 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 00:44:25,464 - INFO - Applying compression before stability calculation
2025-02-14 00:44:25,465 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:44:25,465 - INFO - Input dimensionality check:
2025-02-14 00:44:25,466 - INFO - - Number of dimensions: 2
2025-02-14 00:44:25,466 - INFO -
=== Compression Call ===
2025-02-14 00:44:25,467 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:44:25,468 - INFO - Input dtype: float32
2025-02-14 00:44:25,468 - INFO - Train mode: False
2025-02-14 00:44:25,469 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:44:25,469 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:44:25,470 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:44:25,470 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:44:25,471 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.82it/s]
2025-02-14 00:44:30,226 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:44:30,227 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:44:30,228 - INFO - After semantic compression:
2025-02-14 00:44:30,229 - INFO - - Output shape: (12000, 256)
2025-02-14 00:44:30,230 - INFO - - Output dtype: float32
2025-02-14 00:44:30,230 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:44:30,231 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:30<00:00, 396.26sample/s]
2025-02-14 00:45:00,521 - INFO - Time taken for stability calculation: 35.06 seconds
2025-02-14 00:45:00,522 - INFO - Stability values during calibration (first 10): [-10986.5 -13647.5 -14179.   -6003.  -13268.  -13284.5 -12197.5  -9102.5
   -886.   -5378.5]
2025-02-14 00:45:00,524 - INFO - Calibrated values (first 10): [0.45275406 0.45275406 0.45275406 0.46723494 0.45275406 0.45275406
 0.45275406 0.45275406 0.47980156 0.46723494]
2025-02-14 00:45:00,751 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 00:45:00,752 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 00:45:00,754 - INFO - Final ECE value: 0.001594249845663677
2025-02-14 00:45:00,755 - INFO - Calculating Maximum Calibration Error.
2025-02-14 00:45:00,756 - INFO - Final MCE value: 0.2222222222222222
2025-02-14 00:45:00,757 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 00:45:00,757 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 00:45:00,763 - INFO - Applying compression to training data.
2025-02-14 00:45:00,764 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 00:45:00,764 - INFO - Input dimensionality check:
2025-02-14 00:45:00,765 - INFO - - Number of dimensions: 4
2025-02-14 00:45:00,765 - INFO -
=== Compression Call ===
2025-02-14 00:45:00,766 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 00:45:00,766 - INFO - Input dtype: float32
2025-02-14 00:45:00,767 - INFO - Train mode: True
2025-02-14 00:45:00,767 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 00:45:00,768 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 00:45:00,768 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:45:00,769 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 18.43it/s]
2025-02-14 00:45:16,116 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 00:45:16,118 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 00:45:16,118 - INFO - After semantic compression:
2025-02-14 00:45:16,119 - INFO - - Output shape: (36000, 256)
2025-02-14 00:45:16,119 - INFO - - Output dtype: float32
2025-02-14 00:45:16,120 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 00:45:16,338 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 00:45:16,338 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 00:45:16,339 - INFO - Compression mode: None
2025-02-14 00:45:16,339 - INFO - Compression param: None
2025-02-14 00:45:16,340 - INFO - Library: fast_separation
2025-02-14 00:45:16,340 - INFO - Metric: cosine
2025-02-14 00:45:16,340 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 00:45:16,342 - INFO - Number of unique labels: 10
2025-02-14 00:45:16,342 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 00:45:16,342 - INFO - Initialized GeometricCalibrator with model RandomForestClassifier and fitting function IsotonicRegression.
2025-02-14 00:45:16,343 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 00:45:16,343 - INFO - Sklearn model detected
2025-02-14 00:45:19,249 - INFO - Applying compression before stability calculation
2025-02-14 00:45:19,250 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:45:19,250 - INFO - Input dimensionality check:
2025-02-14 00:45:19,250 - INFO - - Number of dimensions: 2
2025-02-14 00:45:19,251 - INFO -
=== Compression Call ===
2025-02-14 00:45:19,251 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:45:19,252 - INFO - Input dtype: float32
2025-02-14 00:45:19,252 - INFO - Train mode: False
2025-02-14 00:45:19,253 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:45:19,253 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:45:19,254 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:45:19,254 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:45:19,255 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 20.25it/s]
2025-02-14 00:45:23,911 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:45:23,912 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:45:23,912 - INFO - After semantic compression:
2025-02-14 00:45:23,913 - INFO - - Output shape: (12000, 256)
2025-02-14 00:45:23,913 - INFO - - Output dtype: float32
2025-02-14 00:45:23,914 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:45:23,914 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [04:02<00:00, 49.56sample/s]
2025-02-14 00:49:26,065 - INFO - Time taken for stability calculation: 246.82 seconds
2025-02-14 00:49:26,065 - INFO - Stability values (first 5): [-0.01584226 -0.0252474  -0.00962463  0.00039282 -0.00871277]
2025-02-14 00:49:26,236 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 00:49:26,237 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 00:49:28,911 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 00:49:28,911 - INFO - Applying compression before stability calculation
2025-02-14 00:49:28,912 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 00:49:28,912 - INFO - Input dimensionality check:
2025-02-14 00:49:28,913 - INFO - - Number of dimensions: 2
2025-02-14 00:49:28,913 - INFO -
=== Compression Call ===
2025-02-14 00:49:28,914 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 00:49:28,915 - INFO - Input dtype: float32
2025-02-14 00:49:28,915 - INFO - Train mode: False
2025-02-14 00:49:28,916 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 00:49:28,916 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 00:49:28,917 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 00:49:28,917 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:49:28,918 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.51it/s]
2025-02-14 00:49:33,748 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 00:49:33,749 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 00:49:33,750 - INFO - After semantic compression:
2025-02-14 00:49:33,751 - INFO - - Output shape: (12000, 256)
2025-02-14 00:49:33,751 - INFO - - Output dtype: float32
2025-02-14 00:49:33,752 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 00:49:33,753 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [03:59<00:00, 50.05sample/s]
2025-02-14 00:53:33,507 - INFO - Time taken for stability calculation: 244.60 seconds
2025-02-14 00:53:33,508 - INFO - Stability values during calibration (first 10): [-0.01092461 -0.05574757 -0.0052467  -0.00112048  0.02198997  0.00756332
 -0.00458282  0.00461704 -0.01745504 -0.01640213]
2025-02-14 00:53:33,509 - INFO - Calibrated values (first 10): [0.40810811 0.03061224 0.49630845 0.55879495 0.87581699 0.72347826
 0.49630845 0.60697306 0.30324074 0.33576329]
2025-02-14 00:53:33,738 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 00:53:33,739 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 00:53:33,742 - INFO - Final ECE value: 0.015860935918546086
2025-02-14 00:53:33,743 - INFO - Calculating Maximum Calibration Error.
2025-02-14 00:53:33,746 - INFO - Final MCE value: 0.10386473429951687
2025-02-14 00:53:33,770 - INFO - Results saved to output/semantic_calibration/CIFAR10/RF/rs_42/semantic/results.csv

                     Method       ECE       MCE
0      semantic_faiss_exact  0.001594  0.222222
1  semantic_fast_separation  0.015861  0.103865

2025-02-14 00:53:33,774 - INFO - Processing CIFAR10 with RF, random_state=100, compression=semantic, param=mobilenet
2025-02-14 00:53:33,775 - INFO - Loading original data for model training...
2025-02-14 00:53:33,776 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: RF
Compression type: semantic, Parameter: mobilenet

2025-02-14 00:53:37,923 - INFO - Combining and splitting data
2025-02-14 00:53:38,205 - INFO - Data normalization completed
2025-02-14 00:53:38,208 - INFO - Reshaping data for RF model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 00:53:38,946 - INFO - Training RF model...
2025-02-14 00:53:38,954 - INFO - Training new RF model.
2025-02-14 00:53:38,955 - INFO - Model type RF
2025-02-14 00:59:42,240 - INFO - Model saved at output/CIFAR10/100/saved_models/RF_model.keras.
2025-02-14 00:59:42,242 - INFO - Getting model predictions...
2025-02-14 00:59:45,658 - INFO -
=== Compression Initialization ===
2025-02-14 00:59:45,659 - INFO - Original compression_types: ['semantic']
2025-02-14 00:59:45,660 - INFO - Original compression_params: ['mobilenet']
2025-02-14 00:59:45,661 - INFO - Final compression_types: ['semantic']
2025-02-14 00:59:45,662 - INFO - Final compression_params: ['mobilenet']
2025-02-14 00:59:45,662 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 00:59:45,706 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)
2025-02-14 00:59:46,031 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 00:59:46,058 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 00:59:46,078 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 00:59:46,079 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 00:59:46,081 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 00:59:46,081 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 00:59:46,085 - INFO - Applying compression to training data.
2025-02-14 00:59:46,085 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 00:59:46,087 - INFO - Input dimensionality check:
2025-02-14 00:59:46,087 - INFO - - Number of dimensions: 4
2025-02-14 00:59:46,089 - INFO -
=== Compression Call ===
2025-02-14 00:59:46,090 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 00:59:46,090 - INFO - Input dtype: float32
2025-02-14 00:59:46,091 - INFO - Train mode: True
2025-02-14 00:59:46,091 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 00:59:46,092 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 00:59:46,093 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 00:59:46,094 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 18.51it/s]
2025-02-14 01:00:01,385 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:00:01,386 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:00:01,387 - INFO - After semantic compression:
2025-02-14 01:00:01,388 - INFO - - Output shape: (36000, 256)
2025-02-14 01:00:01,389 - INFO - - Output dtype: float32
2025-02-14 01:00:01,390 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:00:01,545 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:00:01,547 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:00:01,548 - INFO - Compression mode: None
2025-02-14 01:00:01,549 - INFO - Compression param: None
2025-02-14 01:00:01,550 - INFO - Library: faiss
2025-02-14 01:00:01,550 - INFO - Metric: cosine
2025-02-14 01:00:01,551 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:00:01,553 - INFO - Number of unique labels: 10
2025-02-14 01:00:01,554 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:00:01,555 - INFO - Initialized GeometricCalibrator with model RandomForestClassifier and fitting function IsotonicRegression.
2025-02-14 01:00:01,556 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:00:01,557 - INFO - Sklearn model detected
2025-02-14 01:00:04,242 - INFO - Applying compression before stability calculation
2025-02-14 01:00:04,243 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:00:04,243 - INFO - Input dimensionality check:
2025-02-14 01:00:04,244 - INFO - - Number of dimensions: 2
2025-02-14 01:00:04,245 - INFO -
=== Compression Call ===
2025-02-14 01:00:04,245 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:00:04,245 - INFO - Input dtype: float32
2025-02-14 01:00:04,246 - INFO - Train mode: False
2025-02-14 01:00:04,246 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:00:04,248 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:00:04,248 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:00:04,248 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:00:04,249 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.20it/s]
2025-02-14 01:00:09,158 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:00:09,159 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:00:09,160 - INFO - After semantic compression:
2025-02-14 01:00:09,161 - INFO - - Output shape: (12000, 256)
2025-02-14 01:00:09,162 - INFO - - Output dtype: float32
2025-02-14 01:00:09,162 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:00:09,163 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:29<00:00, 405.14sample/s]
2025-02-14 01:00:38,789 - INFO - Time taken for stability calculation: 34.55 seconds
2025-02-14 01:00:38,790 - INFO - Stability values (first 5): [ -6178.   -2082.5   -685.5  -6751.5 -11813.5]
2025-02-14 01:00:38,948 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:00:38,949 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:00:41,627 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:00:41,628 - INFO - Applying compression before stability calculation
2025-02-14 01:00:41,628 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:00:41,629 - INFO - Input dimensionality check:
2025-02-14 01:00:41,629 - INFO - - Number of dimensions: 2
2025-02-14 01:00:41,630 - INFO -
=== Compression Call ===
2025-02-14 01:00:41,630 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:00:41,631 - INFO - Input dtype: float32
2025-02-14 01:00:41,631 - INFO - Train mode: False
2025-02-14 01:00:41,632 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:00:41,634 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:00:41,635 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:00:41,635 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:00:41,636 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:06<00:00, 15.27it/s]
2025-02-14 01:00:47,804 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:00:47,805 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:00:47,806 - INFO - After semantic compression:
2025-02-14 01:00:47,807 - INFO - - Output shape: (12000, 256)
2025-02-14 01:00:47,808 - INFO - - Output dtype: float32
2025-02-14 01:00:47,809 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:00:47,810 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:28<00:00, 422.30sample/s]
2025-02-14 01:01:16,231 - INFO - Time taken for stability calculation: 34.60 seconds
2025-02-14 01:01:16,232 - INFO - Stability values during calibration (first 10): [-10904.   -9533.5  -2421.5  -9589.  -13683.  -13308.   -2129.5  -9917.5
   -577.5  -9023. ]
2025-02-14 01:01:16,234 - INFO - Calibrated values (first 10): [0.47206386 0.47206386 0.47206386 0.47206386 0.47206386 0.47206386
 0.47206386 0.47206386 0.47206386 0.47206386]
2025-02-14 01:01:16,463 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:01:16,464 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:01:16,465 - INFO - Final ECE value: 0.00887290099839809
2025-02-14 01:01:16,465 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:01:16,467 - INFO - Final MCE value: 0.07380952380952388
2025-02-14 01:01:16,467 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 01:01:16,467 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 01:01:16,470 - INFO - Applying compression to training data.
2025-02-14 01:01:16,471 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:01:16,471 - INFO - Input dimensionality check:
2025-02-14 01:01:16,472 - INFO - - Number of dimensions: 4
2025-02-14 01:01:16,472 - INFO -
=== Compression Call ===
2025-02-14 01:01:16,472 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:01:16,473 - INFO - Input dtype: float32
2025-02-14 01:01:16,473 - INFO - Train mode: True
2025-02-14 01:01:16,474 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:01:16,474 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:01:16,475 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:01:16,475 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 18.28it/s]
2025-02-14 01:01:31,937 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:01:31,939 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:01:31,939 - INFO - After semantic compression:
2025-02-14 01:01:31,940 - INFO - - Output shape: (36000, 256)
2025-02-14 01:01:31,940 - INFO - - Output dtype: float32
2025-02-14 01:01:31,941 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:01:32,139 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:01:32,139 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:01:32,140 - INFO - Compression mode: None
2025-02-14 01:01:32,140 - INFO - Compression param: None
2025-02-14 01:01:32,140 - INFO - Library: fast_separation
2025-02-14 01:01:32,141 - INFO - Metric: cosine
2025-02-14 01:01:32,142 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:01:32,143 - INFO - Number of unique labels: 10
2025-02-14 01:01:32,143 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:01:32,144 - INFO - Initialized GeometricCalibrator with model RandomForestClassifier and fitting function IsotonicRegression.
2025-02-14 01:01:32,145 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:01:32,145 - INFO - Sklearn model detected
2025-02-14 01:01:34,904 - INFO - Applying compression before stability calculation
2025-02-14 01:01:34,905 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:01:34,906 - INFO - Input dimensionality check:
2025-02-14 01:01:34,907 - INFO - - Number of dimensions: 2
2025-02-14 01:01:34,908 - INFO -
=== Compression Call ===
2025-02-14 01:01:34,908 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:01:34,909 - INFO - Input dtype: float32
2025-02-14 01:01:34,909 - INFO - Train mode: False
2025-02-14 01:01:34,911 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:01:34,912 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:01:34,913 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:01:34,913 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:01:34,914 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 17.00it/s]
2025-02-14 01:01:40,459 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:01:40,460 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:01:40,460 - INFO - After semantic compression:
2025-02-14 01:01:40,461 - INFO - - Output shape: (12000, 256)
2025-02-14 01:01:40,461 - INFO - - Output dtype: float32
2025-02-14 01:01:40,462 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:01:40,462 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [04:03<00:00, 49.22sample/s]
2025-02-14 01:05:44,252 - INFO - Time taken for stability calculation: 249.35 seconds
2025-02-14 01:05:44,252 - INFO - Stability values (first 5): [-1.05889440e-02 -2.83296108e-02  1.88686252e-02 -1.96695328e-06
 -1.26808882e-03]
2025-02-14 01:05:44,440 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:05:44,440 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:05:47,561 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:05:47,561 - INFO - Applying compression before stability calculation
2025-02-14 01:05:47,562 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:05:47,562 - INFO - Input dimensionality check:
2025-02-14 01:05:47,563 - INFO - - Number of dimensions: 2
2025-02-14 01:05:47,563 - INFO -
=== Compression Call ===
2025-02-14 01:05:47,564 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:05:47,565 - INFO - Input dtype: float32
2025-02-14 01:05:47,565 - INFO - Train mode: False
2025-02-14 01:05:47,566 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:05:47,567 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:05:47,568 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:05:47,568 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:05:47,569 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.63it/s]
2025-02-14 01:05:52,370 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:05:52,371 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:05:52,371 - INFO - After semantic compression:
2025-02-14 01:05:52,372 - INFO - - Output shape: (12000, 256)
2025-02-14 01:05:52,372 - INFO - - Output dtype: float32
2025-02-14 01:05:52,373 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:05:52,373 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [04:14<00:00, 47.21sample/s]
2025-02-14 01:10:06,536 - INFO - Time taken for stability calculation: 258.97 seconds
2025-02-14 01:10:06,536 - INFO - Stability values during calibration (first 10): [-0.01792067  0.01009521  0.00405213 -0.00418413 -0.01382682  0.01619381
 -0.01544413 -0.01354089 -0.01328582 -0.01155674]
2025-02-14 01:10:06,538 - INFO - Calibrated values (first 10): [0.24545455 0.7704918  0.64881475 0.53017241 0.31467662 0.82
 0.25583658 0.31467662 0.31467662 0.37177281]
2025-02-14 01:10:06,772 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:10:06,773 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:10:06,776 - INFO - Final ECE value: 0.02076597310493756
2025-02-14 01:10:06,776 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:10:06,782 - INFO - Final MCE value: 0.06608961338970765
2025-02-14 01:10:06,811 - INFO - Results saved to output/semantic_calibration/CIFAR10/RF/rs_100/semantic/results.csv

                     Method       ECE      MCE
0      semantic_faiss_exact  0.008873  0.07381
1  semantic_fast_separation  0.020766  0.06609

2025-02-14 01:10:06,818 - INFO - Processing CIFAR10 with GB, random_state=2, compression=semantic, param=mobilenet
2025-02-14 01:10:06,819 - INFO - Loading original data for model training...
2025-02-14 01:10:06,819 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: GB
Compression type: semantic, Parameter: mobilenet

2025-02-14 01:10:11,401 - INFO - Combining and splitting data
2025-02-14 01:10:11,695 - INFO - Data normalization completed
2025-02-14 01:10:11,698 - INFO - Reshaping data for GB model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 01:10:12,470 - INFO - Training GB model...
2025-02-14 01:10:12,476 - INFO - Training new GB model.
2025-02-14 01:10:12,477 - INFO - Model type GB
2025-02-14 01:14:01,089 - INFO - Model saved at output/CIFAR10/2/saved_models/GB_model.keras.
2025-02-14 01:14:01,091 - INFO - Getting model predictions...
2025-02-14 01:14:02,059 - INFO -
=== Compression Initialization ===
2025-02-14 01:14:02,060 - INFO - Original compression_types: ['semantic']
2025-02-14 01:14:02,061 - INFO - Original compression_params: ['mobilenet']
2025-02-14 01:14:02,061 - INFO - Final compression_types: ['semantic']
2025-02-14 01:14:02,062 - INFO - Final compression_params: ['mobilenet']
2025-02-14 01:14:02,062 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 01:14:02,106 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)
2025-02-14 01:14:02,365 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 01:14:02,386 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 01:14:02,425 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 01:14:02,427 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 01:14:02,429 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 01:14:02,430 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 01:14:02,437 - INFO - Applying compression to training data.
2025-02-14 01:14:02,439 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:14:02,440 - INFO - Input dimensionality check:
2025-02-14 01:14:02,441 - INFO - - Number of dimensions: 4
2025-02-14 01:14:02,443 - INFO -
=== Compression Call ===
2025-02-14 01:14:02,444 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:14:02,446 - INFO - Input dtype: float32
2025-02-14 01:14:02,448 - INFO - Train mode: True
2025-02-14 01:14:02,450 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:14:02,451 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:14:02,453 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:14:02,455 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 17.73it/s]
2025-02-14 01:14:18,412 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:14:18,413 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:14:18,414 - INFO - After semantic compression:
2025-02-14 01:14:18,414 - INFO - - Output shape: (36000, 256)
2025-02-14 01:14:18,415 - INFO - - Output dtype: float32
2025-02-14 01:14:18,416 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:14:18,580 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:14:18,581 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:14:18,581 - INFO - Compression mode: None
2025-02-14 01:14:18,582 - INFO - Compression param: None
2025-02-14 01:14:18,582 - INFO - Library: faiss
2025-02-14 01:14:18,583 - INFO - Metric: cosine
2025-02-14 01:14:18,584 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:14:18,585 - INFO - Number of unique labels: 10
2025-02-14 01:14:18,586 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:14:18,587 - INFO - Initialized GeometricCalibrator with model GradientBoostingClassifier and fitting function IsotonicRegression.
2025-02-14 01:14:18,587 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:14:18,588 - INFO - Sklearn model detected
2025-02-14 01:14:19,570 - INFO - Applying compression before stability calculation
2025-02-14 01:14:19,571 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:14:19,572 - INFO - Input dimensionality check:
2025-02-14 01:14:19,572 - INFO - - Number of dimensions: 2
2025-02-14 01:14:19,573 - INFO -
=== Compression Call ===
2025-02-14 01:14:19,574 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:14:19,574 - INFO - Input dtype: float32
2025-02-14 01:14:19,575 - INFO - Train mode: False
2025-02-14 01:14:19,575 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:14:19,577 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:14:19,578 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:14:19,578 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:14:19,579 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 20.03it/s]
2025-02-14 01:14:24,285 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:14:24,287 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:14:24,288 - INFO - After semantic compression:
2025-02-14 01:14:24,289 - INFO - - Output shape: (12000, 256)
2025-02-14 01:14:24,290 - INFO - - Output dtype: float32
2025-02-14 01:14:24,290 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:14:24,291 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:31<00:00, 380.06sample/s]
2025-02-14 01:14:55,871 - INFO - Time taken for stability calculation: 36.30 seconds
2025-02-14 01:14:55,872 - INFO - Stability values (first 5): [ -3957.   -6508.  -15478.5    960.  -14445. ]
2025-02-14 01:14:56,027 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:14:56,027 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:14:56,914 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:14:56,915 - INFO - Applying compression before stability calculation
2025-02-14 01:14:56,916 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:14:56,916 - INFO - Input dimensionality check:
2025-02-14 01:14:56,917 - INFO - - Number of dimensions: 2
2025-02-14 01:14:56,917 - INFO -
=== Compression Call ===
2025-02-14 01:14:56,918 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:14:56,918 - INFO - Input dtype: float32
2025-02-14 01:14:56,919 - INFO - Train mode: False
2025-02-14 01:14:56,919 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:14:56,920 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:14:56,920 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:14:56,921 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:14:56,921 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.88it/s]
2025-02-14 01:15:01,662 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:15:01,663 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:15:01,664 - INFO - After semantic compression:
2025-02-14 01:15:01,664 - INFO - - Output shape: (12000, 256)
2025-02-14 01:15:01,665 - INFO - - Output dtype: float32
2025-02-14 01:15:01,665 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:15:01,666 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:29<00:00, 403.70sample/s]
2025-02-14 01:15:31,395 - INFO - Time taken for stability calculation: 34.48 seconds
2025-02-14 01:15:31,396 - INFO - Stability values during calibration (first 10): [ -6882.5  -6889.5  -2104.5 -14617.5   -368.   -7796.     563.   -7959.5
 -15348.   -5639.5]
2025-02-14 01:15:31,397 - INFO - Calibrated values (first 10): [0.45498295 0.45498295 0.4561856  0.42467719 0.4561856  0.45498295
 0.4561856  0.45498295 0.42467719 0.4561856 ]
2025-02-14 01:15:31,625 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:15:31,626 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:15:31,628 - INFO - Final ECE value: 0.008363958424540355
2025-02-14 01:15:31,628 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:15:31,630 - INFO - Final MCE value: 0.7846374730796841
2025-02-14 01:15:31,631 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 01:15:31,631 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 01:15:31,635 - INFO - Applying compression to training data.
2025-02-14 01:15:31,635 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:15:31,636 - INFO - Input dimensionality check:
2025-02-14 01:15:31,636 - INFO - - Number of dimensions: 4
2025-02-14 01:15:31,638 - INFO -
=== Compression Call ===
2025-02-14 01:15:31,638 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:15:31,639 - INFO - Input dtype: float32
2025-02-14 01:15:31,639 - INFO - Train mode: True
2025-02-14 01:15:31,640 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:15:31,641 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:15:31,643 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:15:31,643 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:18<00:00, 15.17it/s]
2025-02-14 01:15:50,279 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:15:50,281 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:15:50,282 - INFO - After semantic compression:
2025-02-14 01:15:50,283 - INFO - - Output shape: (36000, 256)
2025-02-14 01:15:50,283 - INFO - - Output dtype: float32
2025-02-14 01:15:50,284 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:15:50,459 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:15:50,460 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:15:50,461 - INFO - Compression mode: None
2025-02-14 01:15:50,461 - INFO - Compression param: None
2025-02-14 01:15:50,462 - INFO - Library: fast_separation
2025-02-14 01:15:50,463 - INFO - Metric: cosine
2025-02-14 01:15:50,463 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:15:50,465 - INFO - Number of unique labels: 10
2025-02-14 01:15:50,465 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:15:50,466 - INFO - Initialized GeometricCalibrator with model GradientBoostingClassifier and fitting function IsotonicRegression.
2025-02-14 01:15:50,466 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:15:50,466 - INFO - Sklearn model detected
2025-02-14 01:15:51,361 - INFO - Applying compression before stability calculation
2025-02-14 01:15:51,362 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:15:51,362 - INFO - Input dimensionality check:
2025-02-14 01:15:51,363 - INFO - - Number of dimensions: 2
2025-02-14 01:15:51,364 - INFO -
=== Compression Call ===
2025-02-14 01:15:51,364 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:15:51,365 - INFO - Input dtype: float32
2025-02-14 01:15:51,365 - INFO - Train mode: False
2025-02-14 01:15:51,366 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:15:51,366 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:15:51,367 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:15:51,367 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:15:51,368 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.44it/s]
2025-02-14 01:15:56,479 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:15:56,481 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:15:56,481 - INFO - After semantic compression:
2025-02-14 01:15:56,482 - INFO - - Output shape: (12000, 256)
2025-02-14 01:15:56,483 - INFO - - Output dtype: float32
2025-02-14 01:15:56,484 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:15:56,485 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [04:10<00:00, 48.00sample/s]
2025-02-14 01:20:06,505 - INFO - Time taken for stability calculation: 255.14 seconds
2025-02-14 01:20:06,506 - INFO - Stability values (first 5): [ 0.00346032 -0.00409222  0.00329363 -0.02049071  0.00710896]
2025-02-14 01:20:06,698 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:20:06,699 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:20:07,693 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:20:07,693 - INFO - Applying compression before stability calculation
2025-02-14 01:20:07,694 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:20:07,695 - INFO - Input dimensionality check:
2025-02-14 01:20:07,696 - INFO - - Number of dimensions: 2
2025-02-14 01:20:07,696 - INFO -
=== Compression Call ===
2025-02-14 01:20:07,697 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:20:07,698 - INFO - Input dtype: float32
2025-02-14 01:20:07,699 - INFO - Train mode: False
2025-02-14 01:20:07,700 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:20:07,701 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:20:07,702 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:20:07,702 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:20:07,703 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.66it/s]
2025-02-14 01:20:12,757 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:20:12,758 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:20:12,759 - INFO - After semantic compression:
2025-02-14 01:20:12,761 - INFO - - Output shape: (12000, 256)
2025-02-14 01:20:12,762 - INFO - - Output dtype: float32
2025-02-14 01:20:12,763 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:20:12,765 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [04:26<00:00, 45.10sample/s]
2025-02-14 01:24:38,853 - INFO - Time taken for stability calculation: 271.16 seconds
2025-02-14 01:24:38,854 - INFO - Stability values during calibration (first 10): [ 0.01298371 -0.00152883 -0.00353608 -0.01853108 -0.0327141  -0.00683263
 -0.00896749 -0.01688612 -0.01209396  0.00387594]
2025-02-14 01:24:38,856 - INFO - Calibrated values (first 10): [0.78409091 0.5531804  0.50595238 0.27456647 0.11355311 0.47444751
 0.41458733 0.29343066 0.40695915 0.63841163]
2025-02-14 01:24:39,094 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:24:39,095 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:24:39,099 - INFO - Final ECE value: 0.014390958712696867
2025-02-14 01:24:39,100 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:24:39,103 - INFO - Final MCE value: 0.0625
2025-02-14 01:24:39,126 - INFO - Results saved to output/semantic_calibration/CIFAR10/GB/rs_2/semantic/results.csv

                     Method       ECE       MCE
0      semantic_faiss_exact  0.008364  0.784637
1  semantic_fast_separation  0.014391  0.062500

2025-02-14 01:24:39,130 - INFO - Processing CIFAR10 with GB, random_state=42, compression=semantic, param=mobilenet
2025-02-14 01:24:39,131 - INFO - Loading original data for model training...
2025-02-14 01:24:39,131 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: GB
Compression type: semantic, Parameter: mobilenet

2025-02-14 01:24:42,585 - INFO - Combining and splitting data
2025-02-14 01:24:42,884 - INFO - Data normalization completed
2025-02-14 01:24:42,887 - INFO - Reshaping data for GB model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 01:24:43,661 - INFO - Training GB model...
2025-02-14 01:24:43,668 - INFO - Training new GB model.
2025-02-14 01:24:43,669 - INFO - Model type GB
2025-02-14 01:28:36,328 - INFO - Model saved at output/CIFAR10/42/saved_models/GB_model.keras.
2025-02-14 01:28:36,329 - INFO - Getting model predictions...
2025-02-14 01:28:37,381 - INFO -
=== Compression Initialization ===
2025-02-14 01:28:37,381 - INFO - Original compression_types: ['semantic']
2025-02-14 01:28:37,382 - INFO - Original compression_params: ['mobilenet']
2025-02-14 01:28:37,382 - INFO - Final compression_types: ['semantic']
2025-02-14 01:28:37,383 - INFO - Final compression_params: ['mobilenet']
2025-02-14 01:28:37,383 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 01:28:37,410 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)
2025-02-14 01:28:37,914 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 01:28:37,936 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 01:28:37,970 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 01:28:37,971 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 01:28:37,972 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 01:28:37,973 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 01:28:37,979 - INFO - Applying compression to training data.
2025-02-14 01:28:37,980 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:28:37,981 - INFO - Input dimensionality check:
2025-02-14 01:28:37,982 - INFO - - Number of dimensions: 4
2025-02-14 01:28:37,983 - INFO -
=== Compression Call ===
2025-02-14 01:28:37,983 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:28:37,984 - INFO - Input dtype: float32
2025-02-14 01:28:37,985 - INFO - Train mode: True
2025-02-14 01:28:37,986 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:28:37,987 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:28:37,988 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:28:37,989 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 17.64it/s]
2025-02-14 01:28:54,025 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:28:54,027 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:28:54,028 - INFO - After semantic compression:
2025-02-14 01:28:54,029 - INFO - - Output shape: (36000, 256)
2025-02-14 01:28:54,030 - INFO - - Output dtype: float32
2025-02-14 01:28:54,031 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:28:54,194 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:28:54,195 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:28:54,196 - INFO - Compression mode: None
2025-02-14 01:28:54,197 - INFO - Compression param: None
2025-02-14 01:28:54,197 - INFO - Library: faiss
2025-02-14 01:28:54,198 - INFO - Metric: cosine
2025-02-14 01:28:54,199 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:28:54,201 - INFO - Number of unique labels: 10
2025-02-14 01:28:54,202 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:28:54,203 - INFO - Initialized GeometricCalibrator with model GradientBoostingClassifier and fitting function IsotonicRegression.
2025-02-14 01:28:54,204 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:28:54,204 - INFO - Sklearn model detected
2025-02-14 01:28:55,168 - INFO - Applying compression before stability calculation
2025-02-14 01:28:55,168 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:28:55,169 - INFO - Input dimensionality check:
2025-02-14 01:28:55,170 - INFO - - Number of dimensions: 2
2025-02-14 01:28:55,170 - INFO -
=== Compression Call ===
2025-02-14 01:28:55,171 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:28:55,171 - INFO - Input dtype: float32
2025-02-14 01:28:55,172 - INFO - Train mode: False
2025-02-14 01:28:55,173 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:28:55,173 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:28:55,174 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:28:55,175 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:28:55,175 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.72it/s]
2025-02-14 01:28:59,958 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:28:59,960 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:28:59,960 - INFO - After semantic compression:
2025-02-14 01:28:59,962 - INFO - - Output shape: (12000, 256)
2025-02-14 01:28:59,963 - INFO - - Output dtype: float32
2025-02-14 01:28:59,964 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:28:59,965 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:34<00:00, 351.66sample/s]
2025-02-14 01:29:34,095 - INFO - Time taken for stability calculation: 38.93 seconds
2025-02-14 01:29:34,095 - INFO - Stability values (first 5): [  440.  -7708.  -8703.5 -5720.   -753.5]
2025-02-14 01:29:34,246 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:29:34,247 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:29:35,297 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:29:35,298 - INFO - Applying compression before stability calculation
2025-02-14 01:29:35,299 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:29:35,299 - INFO - Input dimensionality check:
2025-02-14 01:29:35,300 - INFO - - Number of dimensions: 2
2025-02-14 01:29:35,301 - INFO -
=== Compression Call ===
2025-02-14 01:29:35,301 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:29:35,301 - INFO - Input dtype: float32
2025-02-14 01:29:35,302 - INFO - Train mode: False
2025-02-14 01:29:35,303 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:29:35,303 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:29:35,304 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:29:35,304 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:29:35,305 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.36it/s]
2025-02-14 01:29:40,441 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:29:40,443 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:29:40,444 - INFO - After semantic compression:
2025-02-14 01:29:40,444 - INFO - - Output shape: (12000, 256)
2025-02-14 01:29:40,445 - INFO - - Output dtype: float32
2025-02-14 01:29:40,446 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:29:40,447 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:31<00:00, 376.33sample/s]
2025-02-14 01:30:12,340 - INFO - Time taken for stability calculation: 37.04 seconds
2025-02-14 01:30:12,340 - INFO - Stability values during calibration (first 10): [ -4944.  -14250.5  -3533.5 -15138.5  -6123.5  -2244.5  -4302.   -3583.
 -13199.5  -5263.5]
2025-02-14 01:30:12,342 - INFO - Calibrated values (first 10): [0.4395917  0.43410129 0.4395917  0.43410129 0.4395917  0.44498022
 0.4395917  0.4395917  0.4395917  0.4395917 ]
2025-02-14 01:30:12,797 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:30:12,798 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:30:12,801 - INFO - Final ECE value: 0.007929708775898882
2025-02-14 01:30:12,802 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:30:12,805 - INFO - Final MCE value: 0.0392222637919587
2025-02-14 01:30:12,805 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 01:30:12,806 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 01:30:12,811 - INFO - Applying compression to training data.
2025-02-14 01:30:12,812 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:30:12,812 - INFO - Input dimensionality check:
2025-02-14 01:30:12,813 - INFO - - Number of dimensions: 4
2025-02-14 01:30:12,814 - INFO -
=== Compression Call ===
2025-02-14 01:30:12,814 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:30:12,815 - INFO - Input dtype: float32
2025-02-14 01:30:12,815 - INFO - Train mode: True
2025-02-14 01:30:12,816 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:30:12,816 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:30:12,819 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:30:12,819 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:15<00:00, 18.12it/s]
2025-02-14 01:30:28,421 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:30:28,422 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:30:28,423 - INFO - After semantic compression:
2025-02-14 01:30:28,423 - INFO - - Output shape: (36000, 256)
2025-02-14 01:30:28,424 - INFO - - Output dtype: float32
2025-02-14 01:30:28,424 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:30:28,561 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:30:28,562 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:30:28,563 - INFO - Compression mode: None
2025-02-14 01:30:28,564 - INFO - Compression param: None
2025-02-14 01:30:28,564 - INFO - Library: fast_separation
2025-02-14 01:30:28,565 - INFO - Metric: cosine
2025-02-14 01:30:28,565 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:30:28,567 - INFO - Number of unique labels: 10
2025-02-14 01:30:28,568 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:30:28,568 - INFO - Initialized GeometricCalibrator with model GradientBoostingClassifier and fitting function IsotonicRegression.
2025-02-14 01:30:28,569 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:30:28,569 - INFO - Sklearn model detected
2025-02-14 01:30:29,533 - INFO - Applying compression before stability calculation
2025-02-14 01:30:29,534 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:30:29,535 - INFO - Input dimensionality check:
2025-02-14 01:30:29,535 - INFO - - Number of dimensions: 2
2025-02-14 01:30:29,536 - INFO -
=== Compression Call ===
2025-02-14 01:30:29,537 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:30:29,537 - INFO - Input dtype: float32
2025-02-14 01:30:29,538 - INFO - Train mode: False
2025-02-14 01:30:29,538 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:30:29,539 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:30:29,539 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:30:29,540 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:30:29,541 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.63it/s]
2025-02-14 01:30:34,345 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:30:34,346 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:30:34,347 - INFO - After semantic compression:
2025-02-14 01:30:34,348 - INFO - - Output shape: (12000, 256)
2025-02-14 01:30:34,349 - INFO - - Output dtype: float32
2025-02-14 01:30:34,350 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:30:34,350 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [05:04<00:00, 39.37sample/s]
2025-02-14 01:35:39,128 - INFO - Time taken for stability calculation: 309.59 seconds
2025-02-14 01:35:39,129 - INFO - Stability values (first 5): [-0.00690955 -0.02163592 -0.00574189 -0.00064611 -0.01046568]
2025-02-14 01:35:39,465 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:35:39,466 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:35:40,593 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:35:40,593 - INFO - Applying compression before stability calculation
2025-02-14 01:35:40,594 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:35:40,594 - INFO - Input dimensionality check:
2025-02-14 01:35:40,594 - INFO - - Number of dimensions: 2
2025-02-14 01:35:40,595 - INFO -
=== Compression Call ===
2025-02-14 01:35:40,595 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:35:40,595 - INFO - Input dtype: float32
2025-02-14 01:35:40,596 - INFO - Train mode: False
2025-02-14 01:35:40,596 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:35:40,596 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:35:40,597 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:35:40,597 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:35:40,598 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.76it/s]
2025-02-14 01:35:45,625 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:35:45,626 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:35:45,627 - INFO - After semantic compression:
2025-02-14 01:35:45,628 - INFO - - Output shape: (12000, 256)
2025-02-14 01:35:45,628 - INFO - - Output dtype: float32
2025-02-14 01:35:45,629 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:35:45,629 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [04:54<00:00, 40.77sample/s]
2025-02-14 01:40:39,986 - INFO - Time taken for stability calculation: 299.39 seconds
2025-02-14 01:40:39,987 - INFO - Stability values during calibration (first 10): [-0.0191738  -0.06180471 -0.00701106 -0.01261061  0.02393985  0.00549024
 -0.01366296 -0.01268905 -0.00832984 -0.01465285]
2025-02-14 01:40:39,989 - INFO - Calibrated values (first 10): [0.26541353 0.02272727 0.44957082 0.39098532 0.90909091 0.68987342
 0.3057377  0.39098532 0.4025974  0.29649123]
2025-02-14 01:40:40,225 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:40:40,226 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:40:40,229 - INFO - Final ECE value: 0.020205109785621195
2025-02-14 01:40:40,230 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:40:40,233 - INFO - Final MCE value: 0.10478693821925134
2025-02-14 01:40:40,255 - INFO - Results saved to output/semantic_calibration/CIFAR10/GB/rs_42/semantic/results.csv

                     Method       ECE       MCE
0      semantic_faiss_exact  0.007930  0.039222
1  semantic_fast_separation  0.020205  0.104787

2025-02-14 01:40:40,260 - INFO - Processing CIFAR10 with GB, random_state=100, compression=semantic, param=mobilenet
2025-02-14 01:40:40,260 - INFO - Loading original data for model training...
2025-02-14 01:40:40,261 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: GB
Compression type: semantic, Parameter: mobilenet

2025-02-14 01:40:43,070 - INFO - Combining and splitting data
2025-02-14 01:40:43,391 - INFO - Data normalization completed
2025-02-14 01:40:43,394 - INFO - Reshaping data for GB model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 01:40:44,193 - INFO - Training GB model...
2025-02-14 01:40:44,201 - INFO - Training new GB model.
2025-02-14 01:40:44,202 - INFO - Model type GB
2025-02-14 01:44:34,194 - INFO - Model saved at output/CIFAR10/100/saved_models/GB_model.keras.
2025-02-14 01:44:34,196 - INFO - Getting model predictions...
2025-02-14 01:44:35,535 - INFO -
=== Compression Initialization ===
2025-02-14 01:44:35,537 - INFO - Original compression_types: ['semantic']
2025-02-14 01:44:35,538 - INFO - Original compression_params: ['mobilenet']
2025-02-14 01:44:35,539 - INFO - Final compression_types: ['semantic']
2025-02-14 01:44:35,552 - INFO - Final compression_params: ['mobilenet']
2025-02-14 01:44:35,553 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 01:44:35,628 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)
2025-02-14 01:44:36,159 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 01:44:36,182 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 01:44:36,216 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 01:44:36,218 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 01:44:36,220 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 01:44:36,222 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 01:44:36,230 - INFO - Applying compression to training data.
2025-02-14 01:44:36,232 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:44:36,234 - INFO - Input dimensionality check:
2025-02-14 01:44:36,235 - INFO - - Number of dimensions: 4
2025-02-14 01:44:36,237 - INFO -
=== Compression Call ===
2025-02-14 01:44:36,239 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:44:36,241 - INFO - Input dtype: float32
2025-02-14 01:44:36,243 - INFO - Train mode: True
2025-02-14 01:44:36,245 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:44:36,247 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:44:36,249 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:44:36,251 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:16<00:00, 17.47it/s]
2025-02-14 01:44:52,458 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:44:52,460 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:44:52,461 - INFO - After semantic compression:
2025-02-14 01:44:52,462 - INFO - - Output shape: (36000, 256)
2025-02-14 01:44:52,462 - INFO - - Output dtype: float32
2025-02-14 01:44:52,464 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:44:52,661 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:44:52,662 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:44:52,663 - INFO - Compression mode: None
2025-02-14 01:44:52,664 - INFO - Compression param: None
2025-02-14 01:44:52,664 - INFO - Library: faiss
2025-02-14 01:44:52,664 - INFO - Metric: cosine
2025-02-14 01:44:52,665 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:44:52,666 - INFO - Number of unique labels: 10
2025-02-14 01:44:52,667 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:44:52,667 - INFO - Initialized GeometricCalibrator with model GradientBoostingClassifier and fitting function IsotonicRegression.
2025-02-14 01:44:52,668 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:44:52,668 - INFO - Sklearn model detected
2025-02-14 01:44:53,741 - INFO - Applying compression before stability calculation
2025-02-14 01:44:53,742 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:44:53,742 - INFO - Input dimensionality check:
2025-02-14 01:44:53,742 - INFO - - Number of dimensions: 2
2025-02-14 01:44:53,743 - INFO -
=== Compression Call ===
2025-02-14 01:44:53,743 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:44:53,743 - INFO - Input dtype: float32
2025-02-14 01:44:53,744 - INFO - Train mode: False
2025-02-14 01:44:53,744 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:44:53,744 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:44:53,745 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:44:53,746 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:44:53,746 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.50it/s]
2025-02-14 01:44:58,841 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:44:58,843 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:44:58,844 - INFO - After semantic compression:
2025-02-14 01:44:58,845 - INFO - - Output shape: (12000, 256)
2025-02-14 01:44:58,846 - INFO - - Output dtype: float32
2025-02-14 01:44:58,847 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:44:58,848 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:41<00:00, 291.97sample/s]
2025-02-14 01:45:39,956 - INFO - Time taken for stability calculation: 46.21 seconds
2025-02-14 01:45:39,957 - INFO - Stability values (first 5): [-8315.  -3473.   -685.5   212.5 -2027. ]
2025-02-14 01:45:40,105 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:45:40,106 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:45:41,175 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:45:41,176 - INFO - Applying compression before stability calculation
2025-02-14 01:45:41,176 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:45:41,177 - INFO - Input dimensionality check:
2025-02-14 01:45:41,177 - INFO - - Number of dimensions: 2
2025-02-14 01:45:41,177 - INFO -
=== Compression Call ===
2025-02-14 01:45:41,178 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:45:41,178 - INFO - Input dtype: float32
2025-02-14 01:45:41,178 - INFO - Train mode: False
2025-02-14 01:45:41,179 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:45:41,179 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:45:41,179 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:45:41,180 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:45:41,180 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.46it/s]
2025-02-14 01:45:46,286 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:45:46,288 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:45:46,289 - INFO - After semantic compression:
2025-02-14 01:45:46,290 - INFO - - Output shape: (12000, 256)
2025-02-14 01:45:46,290 - INFO - - Output dtype: float32
2025-02-14 01:45:46,291 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:45:46,292 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:40<00:00, 298.44sample/s]
2025-02-14 01:46:26,508 - INFO - Time taken for stability calculation: 45.33 seconds
2025-02-14 01:46:26,508 - INFO - Stability values during calibration (first 10): [-10904.   -2739.5  -2421.5  -1503.  -15132.5  -8178.  -15647.  -10064.
   -298.   -4499.5]
2025-02-14 01:46:26,510 - INFO - Calibrated values (first 10): [0.45586215 0.45586215 0.45586215 0.45586215 0.45586215 0.45586215
 0.44915254 0.45586215 0.45586215 0.45586215]
2025-02-14 01:46:26,741 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:46:26,742 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:46:26,744 - INFO - Final ECE value: 0.016373947156255526
2025-02-14 01:46:26,744 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:46:26,745 - INFO - Final MCE value: 0.665097300690521
2025-02-14 01:46:26,746 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 01:46:26,746 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 01:46:26,752 - INFO - Applying compression to training data.
2025-02-14 01:46:26,753 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:46:26,753 - INFO - Input dimensionality check:
2025-02-14 01:46:26,754 - INFO - - Number of dimensions: 4
2025-02-14 01:46:26,755 - INFO -
=== Compression Call ===
2025-02-14 01:46:26,755 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:46:26,755 - INFO - Input dtype: float32
2025-02-14 01:46:26,756 - INFO - Train mode: True
2025-02-14 01:46:26,757 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:46:26,757 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:46:26,757 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:46:26,758 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:16<00:00, 16.84it/s]
2025-02-14 01:46:43,561 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:46:43,562 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:46:43,563 - INFO - After semantic compression:
2025-02-14 01:46:43,564 - INFO - - Output shape: (36000, 256)
2025-02-14 01:46:43,564 - INFO - - Output dtype: float32
2025-02-14 01:46:43,565 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:46:43,824 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:46:43,824 - INFO - Input X_train shape: (36000, 3072)
2025-02-14 01:46:43,825 - INFO - Compression mode: None
2025-02-14 01:46:43,825 - INFO - Compression param: None
2025-02-14 01:46:43,826 - INFO - Library: fast_separation
2025-02-14 01:46:43,826 - INFO - Metric: cosine
2025-02-14 01:46:43,827 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:46:43,828 - INFO - Number of unique labels: 10
2025-02-14 01:46:43,829 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:46:43,829 - INFO - Initialized GeometricCalibrator with model GradientBoostingClassifier and fitting function IsotonicRegression.
2025-02-14 01:46:43,830 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.
2025-02-14 01:46:43,830 - INFO - Sklearn model detected
2025-02-14 01:46:44,916 - INFO - Applying compression before stability calculation
2025-02-14 01:46:44,917 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:46:44,917 - INFO - Input dimensionality check:
2025-02-14 01:46:44,917 - INFO - - Number of dimensions: 2
2025-02-14 01:46:44,918 - INFO -
=== Compression Call ===
2025-02-14 01:46:44,918 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:46:44,918 - INFO - Input dtype: float32
2025-02-14 01:46:44,919 - INFO - Train mode: False
2025-02-14 01:46:44,920 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:46:44,920 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:46:44,921 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:46:44,921 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:46:44,922 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:04<00:00, 19.72it/s]
2025-02-14 01:46:49,710 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:46:49,711 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:46:49,712 - INFO - After semantic compression:
2025-02-14 01:46:49,712 - INFO - - Output shape: (12000, 256)
2025-02-14 01:46:49,713 - INFO - - Output dtype: float32
2025-02-14 01:46:49,713 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:46:49,714 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [05:31<00:00, 36.21sample/s]
2025-02-14 01:52:21,088 - INFO - Time taken for stability calculation: 336.17 seconds
2025-02-14 01:52:21,089 - INFO - Stability values (first 5): [-7.39580393e-03 -1.70484483e-02  8.06152821e-05  2.20271945e-03
 -1.22136474e-02]
2025-02-14 01:52:21,261 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:52:21,262 - INFO - GeometricCalibrator: Calibrating test data.
2025-02-14 01:52:22,443 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:52:22,444 - INFO - Applying compression before stability calculation
2025-02-14 01:52:22,445 - INFO - Input data shape: (12000, 3072), dtype: float32
2025-02-14 01:52:22,446 - INFO - Input dimensionality check:
2025-02-14 01:52:22,447 - INFO - - Number of dimensions: 2
2025-02-14 01:52:22,447 - INFO -
=== Compression Call ===
2025-02-14 01:52:22,448 - INFO - Input X_train shape: (12000, 3072)
2025-02-14 01:52:22,449 - INFO - Input dtype: float32
2025-02-14 01:52:22,449 - INFO - Train mode: False
2025-02-14 01:52:22,450 - INFO - Detected flattened 32x32x3 input; reshaping to (N, 32, 32, 3).
2025-02-14 01:52:22,450 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:52:22,451 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:52:22,452 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:52:22,452 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 18.08it/s]
2025-02-14 01:52:27,673 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:52:27,674 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:52:27,675 - INFO - After semantic compression:
2025-02-14 01:52:27,675 - INFO - - Output shape: (12000, 256)
2025-02-14 01:52:27,676 - INFO - - Output dtype: float32
2025-02-14 01:52:27,677 - INFO - Compressed validation data from (12000, 3072) to (12000, 256)
2025-02-14 01:52:27,677 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [05:44<00:00, 34.87sample/s]
2025-02-14 01:58:11,858 - INFO - Time taken for stability calculation: 349.41 seconds
2025-02-14 01:58:11,859 - INFO - Stability values during calibration (first 10): [-0.00470448  0.0101361  -0.00505039 -0.01197398 -0.0243648   0.0135521
  0.00707233 -0.00585476 -0.02830485 -0.02116418]
2025-02-14 01:58:11,862 - INFO - Calibrated values (first 10): [0.50630252 0.68656716 0.50630252 0.40936556 0.18612637 0.82464455
 0.67061611 0.49250936 0.18612637 0.21538462]
2025-02-14 01:58:12,201 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 01:58:12,202 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 01:58:12,206 - INFO - Final ECE value: 0.02161219594790906
2025-02-14 01:58:12,207 - INFO - Calculating Maximum Calibration Error.
2025-02-14 01:58:12,211 - INFO - Final MCE value: 0.3016561812695002
2025-02-14 01:58:12,238 - INFO - Results saved to output/semantic_calibration/CIFAR10/GB/rs_100/semantic/results.csv

                     Method       ECE       MCE
0      semantic_faiss_exact  0.016374  0.665097
1  semantic_fast_separation  0.021612  0.301656

2025-02-14 01:58:12,245 - INFO - Processing CIFAR10 with cnn, random_state=2, compression=semantic, param=mobilenet
2025-02-14 01:58:12,246 - INFO - Loading original data for model training...
2025-02-14 01:58:12,246 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: cnn
Compression type: semantic, Parameter: mobilenet

2025-02-14 01:58:15,925 - INFO - Combining and splitting data
2025-02-14 01:58:16,339 - INFO - Data normalization completed
2025-02-14 01:58:16,342 - INFO - Training cnn model...
2025-02-14 01:58:16,345 - INFO - Using 45 epochs for training.
2025-02-14 01:58:16,350 - INFO - Loading pre-trained cnn model from output/CIFAR10/2/saved_models/cnn_model.keras.

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-14 01:58:17,089 - INFO - Getting model predictions...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1739491097.582411 2382404 service.cc:145] XLA service 0x7f53a8007fe0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1739491097.582469 2382404 service.cc:153]   StreamExecutor device (0): Host, Default Version
2025-02-14 01:58:17.708042: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.

  1/375 ━━━━━━━━━━━━━━━━━━━━ 7:21 1s/step

I0000 00:00:1739491098.382689 2382404 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

375/375 ━━━━━━━━━━━━━━━━━━━━ 10s 23ms/step

2025-02-14 01:58:27,119 - INFO -
=== Compression Initialization ===
2025-02-14 01:58:27,120 - INFO - Original compression_types: ['semantic']
2025-02-14 01:58:27,121 - INFO - Original compression_params: ['mobilenet']
2025-02-14 01:58:27,121 - INFO - Final compression_types: ['semantic']
2025-02-14 01:58:27,121 - INFO - Final compression_params: ['mobilenet']
2025-02-14 01:58:27,122 - INFO - Loading MobileNetV3 model mobilenetv3_small_100
2025-02-14 01:58:27,147 - INFO - Loading pretrained weights from Hugging Face hub (timm/mobilenetv3_small_100.lamb_in1k)
2025-02-14 01:58:27,476 - INFO - [timm/mobilenetv3_small_100.lamb_in1k] Safe alternative available for 'pytorch_model.bin' (as 'model.safetensors'). Loading weights using safetensors.
2025-02-14 01:58:27,495 - WARNING - Unexpected keys (classifier.bias, classifier.weight, conv_head.bias, conv_head.weight) found while loading pretrained weights. This may be expected if model is being adapted.
2025-02-14 01:58:27,525 - INFO - Initialized mobilenet model for semantic compression
2025-02-14 01:58:27,526 - INFO - Initialize Compression with ['semantic'] and ['mobilenet']
2025-02-14 01:58:27,527 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-14 01:58:27,528 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-14 01:58:27,533 - INFO - Applying compression to training data.
2025-02-14 01:58:27,534 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 01:58:27,535 - INFO - Input dimensionality check:
2025-02-14 01:58:27,536 - INFO - - Number of dimensions: 4
2025-02-14 01:58:27,536 - INFO -
=== Compression Call ===
2025-02-14 01:58:27,537 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:58:27,538 - INFO - Input dtype: float32
2025-02-14 01:58:27,539 - INFO - Train mode: True
2025-02-14 01:58:27,539 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 01:58:27,540 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 01:58:27,541 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:58:27,542 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with mobilenet: 100%|██████████| 282/282 [00:16<00:00, 17.23it/s]
2025-02-14 01:58:43,963 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 01:58:43,965 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 01:58:43,966 - INFO - After semantic compression:
2025-02-14 01:58:43,967 - INFO - - Output shape: (36000, 256)
2025-02-14 01:58:43,968 - INFO - - Output dtype: float32
2025-02-14 01:58:43,969 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 01:58:44,208 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 01:58:44,209 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 01:58:44,210 - INFO - Compression mode: None
2025-02-14 01:58:44,210 - INFO - Compression param: None
2025-02-14 01:58:44,211 - INFO - Library: faiss
2025-02-14 01:58:44,211 - INFO - Metric: cosine
2025-02-14 01:58:44,211 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 01:58:44,212 - INFO - Number of unique labels: 10
2025-02-14 01:58:44,213 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 01:58:44,213 - INFO - Initialized GeometricCalibrator with model Sequential and fitting function IsotonicRegression.
2025-02-14 01:58:44,214 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.

375/375 ━━━━━━━━━━━━━━━━━━━━ 8s 20ms/step

2025-02-14 01:58:52,011 - INFO - Applying compression before stability calculation
2025-02-14 01:58:52,011 - INFO - Input data shape: (12000, 32, 32, 3), dtype: float32
2025-02-14 01:58:52,012 - INFO - Input dimensionality check:
2025-02-14 01:58:52,012 - INFO - - Number of dimensions: 4
2025-02-14 01:58:52,013 - INFO -
=== Compression Call ===
2025-02-14 01:58:52,013 - INFO - Input X_train shape: (12000, 32, 32, 3)
2025-02-14 01:58:52,013 - INFO - Input dtype: float32
2025-02-14 01:58:52,014 - INFO - Train mode: False
2025-02-14 01:58:52,014 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:58:52,014 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:58:52,015 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:58:52,015 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 17.81it/s]
2025-02-14 01:58:57,310 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:58:57,312 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:58:57,313 - INFO - After semantic compression:
2025-02-14 01:58:57,314 - INFO - - Output shape: (12000, 256)
2025-02-14 01:58:57,315 - INFO - - Output dtype: float32
2025-02-14 01:58:57,316 - INFO - Compressed validation data from (12000, 32, 32, 3) to (12000, 256)
2025-02-14 01:58:57,317 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:42<00:00, 283.68sample/s]
2025-02-14 01:59:39,624 - INFO - Time taken for stability calculation: 47.61 seconds
2025-02-14 01:59:39,625 - INFO - Stability values (first 5): [-14424.   -6508.  -10224.5   -631.   -3920.5]
2025-02-14 01:59:39,788 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 01:59:39,789 - INFO - GeometricCalibrator: Calibrating test data.

375/375 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step

2025-02-14 01:59:48,149 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 01:59:48,150 - INFO - Applying compression before stability calculation
2025-02-14 01:59:48,150 - INFO - Input data shape: (12000, 32, 32, 3), dtype: float32
2025-02-14 01:59:48,151 - INFO - Input dimensionality check:
2025-02-14 01:59:48,151 - INFO - - Number of dimensions: 4
2025-02-14 01:59:48,152 - INFO -
=== Compression Call ===
2025-02-14 01:59:48,153 - INFO - Input X_train shape: (12000, 32, 32, 3)
2025-02-14 01:59:48,153 - INFO - Input dtype: float32
2025-02-14 01:59:48,154 - INFO - Train mode: False
2025-02-14 01:59:48,154 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 01:59:48,155 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 01:59:48,155 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 01:59:48,155 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 17.85it/s]
2025-02-14 01:59:53,441 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 01:59:53,444 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 01:59:53,446 - INFO - After semantic compression:
2025-02-14 01:59:53,448 - INFO - - Output shape: (12000, 256)
2025-02-14 01:59:53,450 - INFO - - Output dtype: float32
2025-02-14 01:59:53,453 - INFO - Compressed validation data from (12000, 32, 32, 3) to (12000, 256)
2025-02-14 01:59:53,457 - INFO - Calculating stability using FAISS.
Calculating Stability (FAISS): 100%|██████████| 12000/12000 [00:42<00:00, 284.41sample/s]
2025-02-14 02:00:35,666 - INFO - Time taken for stability calculation: 47.52 seconds
2025-02-14 02:00:35,667 - INFO - Stability values during calibration (first 10): [-1.38425e+04 -7.58100e+03 -1.41400e+03 -6.97850e+03 -3.30500e+03
 -7.79600e+03  2.50000e+00 -2.09500e+02 -1.57740e+04 -1.41600e+04]
2025-02-14 02:00:35,669 - INFO - Calibrated values (first 10): [0.67361182 0.67361182 0.67361182 0.67361182 0.67361182 0.67361182
 0.67361182 0.67361182 0.61666667 0.67361182]
2025-02-14 02:00:35,707 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 02:00:35,708 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 02:00:35,711 - INFO - Final ECE value: 0.005302797186036412
2025-02-14 02:00:35,712 - INFO - Calculating Maximum Calibration Error.
2025-02-14 02:00:35,714 - INFO - Final MCE value: 0.4666666666666668
2025-02-14 02:00:35,715 - INFO - Running fast_separation calibration with semantic compression...
2025-02-14 02:00:35,716 - INFO - Initializing StabilitySpace with fast_separation library and cosine metric.
2025-02-14 02:00:35,719 - INFO - Applying compression to training data.
2025-02-14 02:00:35,720 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-14 02:00:35,721 - INFO - Input dimensionality check:
2025-02-14 02:00:35,721 - INFO - - Number of dimensions: 4
2025-02-14 02:00:35,722 - INFO -
=== Compression Call ===
2025-02-14 02:00:35,722 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 02:00:35,723 - INFO - Input dtype: float32
2025-02-14 02:00:35,723 - INFO - Train mode: True
2025-02-14 02:00:35,723 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-14 02:00:35,724 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-14 02:00:35,724 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 02:00:35,726 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting fast_separation calibration ===
Configuration: {'library': 'fast_separation', 'mode': None}

Processing with mobilenet: 100%|██████████| 282/282 [00:16<00:00, 16.82it/s]
2025-02-14 02:00:52,561 - INFO - Generated semantic embeddings of shape (36000, 256)
2025-02-14 02:00:52,563 - INFO - Applied semantic compression. New shape: (36000, 256)
2025-02-14 02:00:52,564 - INFO - After semantic compression:
2025-02-14 02:00:52,566 - INFO - - Output shape: (36000, 256)
2025-02-14 02:00:52,567 - INFO - - Output dtype: float32
2025-02-14 02:00:52,568 - INFO - Compression applied. Original shape: (36000, 32, 32, 3), Compressed shape: (36000, 256)
2025-02-14 02:00:52,762 - INFO -
=== GeometricCalibrator Initialization ===
2025-02-14 02:00:52,763 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-14 02:00:52,763 - INFO - Compression mode: None
2025-02-14 02:00:52,764 - INFO - Compression param: None
2025-02-14 02:00:52,764 - INFO - Library: fast_separation
2025-02-14 02:00:52,764 - INFO - Metric: cosine
2025-02-14 02:00:52,765 - INFO - Initialized GeometricCalibrator with n_classes=None, bins=15, temperature=1.0
2025-02-14 02:00:52,766 - INFO - Number of unique labels: 10
2025-02-14 02:00:52,767 - INFO - GeometricCalibrator: Using custom StabilitySpace provided by user.
2025-02-14 02:00:52,767 - INFO - Initialized GeometricCalibrator with model Sequential and fitting function IsotonicRegression.
2025-02-14 02:00:52,768 - INFO - GeometricCalibrator: Fitting with validation data using balanced accuracy and rounded stability.

375/375 ━━━━━━━━━━━━━━━━━━━━ 7s 20ms/step

2025-02-14 02:01:00,460 - INFO - Applying compression before stability calculation
2025-02-14 02:01:00,460 - INFO - Input data shape: (12000, 32, 32, 3), dtype: float32
2025-02-14 02:01:00,461 - INFO - Input dimensionality check:
2025-02-14 02:01:00,461 - INFO - - Number of dimensions: 4
2025-02-14 02:01:00,462 - INFO -
=== Compression Call ===
2025-02-14 02:01:00,462 - INFO - Input X_train shape: (12000, 32, 32, 3)
2025-02-14 02:01:00,463 - INFO - Input dtype: float32
2025-02-14 02:01:00,463 - INFO - Train mode: False
2025-02-14 02:01:00,464 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 02:01:00,464 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 02:01:00,464 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 02:01:00,465 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 17.92it/s]
2025-02-14 02:01:05,727 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 02:01:05,728 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 02:01:05,729 - INFO - After semantic compression:
2025-02-14 02:01:05,729 - INFO - - Output shape: (12000, 256)
2025-02-14 02:01:05,730 - INFO - - Output dtype: float32
2025-02-14 02:01:05,731 - INFO - Compressed validation data from (12000, 32, 32, 3) to (12000, 256)
2025-02-14 02:01:05,731 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [05:41<00:00, 35.09sample/s]
2025-02-14 02:06:47,719 - INFO - Time taken for stability calculation: 347.26 seconds
2025-02-14 02:06:47,720 - INFO - Stability values (first 5): [ 0.0057891  -0.00542715  0.00174904 -0.01063296 -0.00013161]
2025-02-14 02:06:47,905 - INFO - GeometricCalibrator: Successfully fitted using stability-accuracy pairs and IsotonicRegression.
2025-02-14 02:06:47,906 - INFO - GeometricCalibrator: Calibrating test data.

375/375 ━━━━━━━━━━━━━━━━━━━━ 8s 22ms/step

2025-02-14 02:06:56,233 - INFO - Starting calibration for 12000 samples and 10 classes.
2025-02-14 02:06:56,233 - INFO - Applying compression before stability calculation
2025-02-14 02:06:56,234 - INFO - Input data shape: (12000, 32, 32, 3), dtype: float32
2025-02-14 02:06:56,234 - INFO - Input dimensionality check:
2025-02-14 02:06:56,235 - INFO - - Number of dimensions: 4
2025-02-14 02:06:56,235 - INFO -
=== Compression Call ===
2025-02-14 02:06:56,236 - INFO - Input X_train shape: (12000, 32, 32, 3)
2025-02-14 02:06:56,236 - INFO - Input dtype: float32
2025-02-14 02:06:56,236 - INFO - Train mode: False
2025-02-14 02:06:56,237 - INFO - Detected 4D input: batch=12000, height=32, width=32, channels=3
2025-02-14 02:06:56,237 - INFO - Keeping multi-channel images in 4D. Shape remains: (12000, 32, 32, 3)
2025-02-14 02:06:56,237 - INFO -
Applying semantic compression with parameter mobilenet
2025-02-14 02:06:56,238 - INFO - Before compression shape: (12000, 32, 32, 3)
Processing with mobilenet: 100%|██████████| 94/94 [00:05<00:00, 17.92it/s]
2025-02-14 02:07:01,507 - INFO - Generated semantic embeddings of shape (12000, 256)
2025-02-14 02:07:01,508 - INFO - Applied semantic compression. New shape: (12000, 256)
2025-02-14 02:07:01,509 - INFO - After semantic compression:
2025-02-14 02:07:01,509 - INFO - - Output shape: (12000, 256)
2025-02-14 02:07:01,510 - INFO - - Output dtype: float32
2025-02-14 02:07:01,510 - INFO - Compressed validation data from (12000, 32, 32, 3) to (12000, 256)
2025-02-14 02:07:01,511 - INFO - Calculating stability using fast_separation.
Calculating Stability (fast_separation): 100%|██████████| 12000/12000 [05:38<00:00, 35.48sample/s]
2025-02-14 02:12:39,689 - INFO - Time taken for stability calculation: 343.46 seconds
2025-02-14 02:12:39,690 - INFO - Stability values during calibration (first 10): [ 0.00701723  0.00654024 -0.0144144   0.00978595  0.01227257 -0.00451782
 -0.0152531  -0.01295143 -0.02884516 -0.01666951]
2025-02-14 02:12:39,692 - INFO - Calibrated values (first 10): [0.83023649 0.83023649 0.53735926 0.85263158 0.85774059 0.69896492
 0.53735926 0.53735926 0.36170213 0.51956182]
2025-02-14 02:12:39,729 - INFO - GeometricCalibrator: Calibration successful.
2025-02-14 02:12:39,730 - INFO - Starting Expected Calibration Error (ECE) calculation.
2025-02-14 02:12:39,734 - INFO - Final ECE value: 0.015440969296484686
2025-02-14 02:12:39,734 - INFO - Calculating Maximum Calibration Error.
2025-02-14 02:12:39,738 - INFO - Final MCE value: 0.5772318408132818
2025-02-14 02:12:39,759 - INFO - Results saved to output/semantic_calibration/CIFAR10/cnn/rs_2/semantic/results.csv

                     Method       ECE       MCE
0      semantic_faiss_exact  0.005303  0.466667
1  semantic_fast_separation  0.015441  0.577232

2025-02-14 02:12:39,764 - INFO - Processing CIFAR10 with cnn, random_state=42, compression=semantic, param=mobilenet
2025-02-14 02:12:39,765 - INFO - Loading original data for model training...
2025-02-14 02:12:39,765 - INFO - Loading dataset: CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: cnn
Compression type: semantic, Parameter: mobilenet

2025-02-14 02:12:43,749 - INFO - Combining and splitting data
2025-02-14 02:12:44,147 - INFO - Data normalization completed
2025-02-14 02:12:44,151 - INFO - Training cnn model...
2025-02-14 02:12:44,154 - INFO - Using 45 epochs for training.
2025-02-14 02:12:44,159 - INFO - Training new cnn model.
/home/itayab/.conda/envs/import_env/lib/python3.9/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-02-14 02:12:44,268 - INFO - Model type cnn

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)
Epoch 1/45
1125/1125 - 88s - 78ms/step - accuracy: 0.4514 - loss: 1.5142 - val_accuracy: 0.5591 - val_loss: 1.2797
Epoch 2/45
1125/1125 - 86s - 76ms/step - accuracy: 0.5874 - loss: 1.1625 - val_accuracy: 0.6126 - val_loss: 1.1485
Epoch 3/45
1125/1125 - 85s - 75ms/step - accuracy: 0.6596 - loss: 0.9639 - val_accuracy: 0.6409 - val_loss: 1.0263
Epoch 4/45
1125/1125 - 85s - 75ms/step - accuracy: 0.7147 - loss: 0.8051 - val_accuracy: 0.6467 - val_loss: 1.0360
Epoch 5/45
1125/1125 - 87s - 77ms/step - accuracy: 0.7656 - loss: 0.6625 - val_accuracy: 0.6782 - val_loss: 0.9452
Epoch 6/45
1125/1125 - 85s - 76ms/step - accuracy: 0.8119 - loss: 0.5377 - val_accuracy: 0.6643 - val_loss: 1.0103
Epoch 7/45
1125/1125 - 144s - 128ms/step - accuracy: 0.8446 - loss: 0.4451 - val_accuracy: 0.6802 - val_loss: 0.9848
Epoch 8/45
1125/1125 - 72s - 64ms/step - accuracy: 0.8732 - loss: 0.3650 - val_accuracy: 0.6741 - val_loss: 1.0163
Epoch 9/45
1125/1125 - 86s - 76ms/step - accuracy: 0.8933 - loss: 0.3078 - val_accuracy: 0.6763 - val_loss: 1.0642
Epoch 10/45
1125/1125 - 87s - 77ms/step - accuracy: 0.9062 - loss: 0.2671 - val_accuracy: 0.6783 - val_loss: 1.1291
Epoch 11/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9176 - loss: 0.2434 - val_accuracy: 0.6846 - val_loss: 1.1023
Epoch 12/45
1125/1125 - 77s - 69ms/step - accuracy: 0.9266 - loss: 0.2193 - val_accuracy: 0.6740 - val_loss: 1.1754
Epoch 13/45
1125/1125 - 78s - 69ms/step - accuracy: 0.9307 - loss: 0.2095 - val_accuracy: 0.6825 - val_loss: 1.1437
Epoch 14/45
1125/1125 - 77s - 68ms/step - accuracy: 0.9356 - loss: 0.1917 - val_accuracy: 0.6852 - val_loss: 1.1735
Epoch 15/45
1125/1125 - 78s - 70ms/step - accuracy: 0.9401 - loss: 0.1807 - val_accuracy: 0.6807 - val_loss: 1.3080
Epoch 16/45
1125/1125 - 80s - 71ms/step - accuracy: 0.9421 - loss: 0.1781 - val_accuracy: 0.6790 - val_loss: 1.3058
Epoch 17/45
1125/1125 - 78s - 69ms/step - accuracy: 0.9474 - loss: 0.1579 - val_accuracy: 0.6784 - val_loss: 1.3268
Epoch 18/45
1125/1125 - 79s - 70ms/step - accuracy: 0.9478 - loss: 0.1610 - val_accuracy: 0.6782 - val_loss: 1.3527
Epoch 19/45
1125/1125 - 76s - 68ms/step - accuracy: 0.9487 - loss: 0.1616 - val_accuracy: 0.6778 - val_loss: 1.2872
Epoch 20/45
1125/1125 - 77s - 68ms/step - accuracy: 0.9525 - loss: 0.1483 - val_accuracy: 0.6777 - val_loss: 1.3398
Epoch 21/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9559 - loss: 0.1378 - val_accuracy: 0.6818 - val_loss: 1.4123
Epoch 22/45
1125/1125 - 78s - 70ms/step - accuracy: 0.9562 - loss: 0.1378 - val_accuracy: 0.6718 - val_loss: 1.4227
Epoch 23/45
1125/1125 - 78s - 69ms/step - accuracy: 0.9538 - loss: 0.1455 - val_accuracy: 0.6827 - val_loss: 1.3059
Epoch 24/45
1125/1125 - 80s - 71ms/step - accuracy: 0.9571 - loss: 0.1338 - val_accuracy: 0.6772 - val_loss: 1.3859
Epoch 25/45
1125/1125 - 77s - 69ms/step - accuracy: 0.9628 - loss: 0.1244 - val_accuracy: 0.6815 - val_loss: 1.4671
Epoch 26/45
1125/1125 - 84s - 75ms/step - accuracy: 0.9582 - loss: 0.1320 - val_accuracy: 0.6786 - val_loss: 1.3912
Epoch 27/45
1125/1125 - 82s - 73ms/step - accuracy: 0.9615 - loss: 0.1265 - val_accuracy: 0.6703 - val_loss: 1.5697
Epoch 28/45
1125/1125 - 83s - 73ms/step - accuracy: 0.9592 - loss: 0.1320 - val_accuracy: 0.6704 - val_loss: 1.4853
Epoch 29/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9637 - loss: 0.1204 - val_accuracy: 0.6802 - val_loss: 1.3678
Epoch 30/45
1125/1125 - 74s - 66ms/step - accuracy: 0.9629 - loss: 0.1210 - val_accuracy: 0.6631 - val_loss: 1.6434
Epoch 31/45
1125/1125 - 80s - 72ms/step - accuracy: 0.9647 - loss: 0.1194 - val_accuracy: 0.6800 - val_loss: 1.3865
Epoch 32/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9652 - loss: 0.1154 - val_accuracy: 0.6787 - val_loss: 1.5548
Epoch 33/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9661 - loss: 0.1151 - val_accuracy: 0.6778 - val_loss: 1.4338
Epoch 34/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9653 - loss: 0.1174 - val_accuracy: 0.6794 - val_loss: 1.4496
Epoch 35/45
1125/1125 - 79s - 70ms/step - accuracy: 0.9681 - loss: 0.1097 - val_accuracy: 0.6802 - val_loss: 1.4547
Epoch 36/45
1125/1125 - 80s - 71ms/step - accuracy: 0.9658 - loss: 0.1160 - val_accuracy: 0.6796 - val_loss: 1.5338
Epoch 37/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9668 - loss: 0.1140 - val_accuracy: 0.6840 - val_loss: 1.6013
Epoch 38/45
1125/1125 - 81s - 72ms/step - accuracy: 0.9695 - loss: 0.1072 - val_accuracy: 0.6785 - val_loss: 1.4168
Epoch 39/45
1125/1125 - 78s - 69ms/step - accuracy: 0.9692 - loss: 0.1093 - val_accuracy: 0.6798 - val_loss: 1.5163
Epoch 40/45

In [6]:
# # Run all experiments
# # run_experiments(
# #     datasets=["CIFAR10", "MNIST"],
# #     models=["RF", "GB"],
# #     random_states=[2, 42, 100],  # Try multiple seeds
# #     compression_types=["semantic"],  # Try both compression types
# #     compression_params={"semantic": "efficientnet"}  # Define parameters per type
# # )
# 
# run_experiments(
#     datasets=["CIFAR10", "MNIST"],
#     models=["RF", "GB"],
#     random_states=[2, 42, 100],  # Try multiple seeds
#     compression_types=["semantic"],  # Try both compression types
#     compression_params={"semantic": "clip"}  # Define parameters per type
# )
# 
# run_experiments(
#     datasets=["CIFAR10", "MNIST"],
#     models=["RF", "GB"],
#     random_states=[2, 42, 100],  # Try multiple seeds
#     compression_types=["semantic"],  # Try both compression types
#     compression_params={"semantic": "mobilenet"}  # Define parameters per type
# )
# # Or run a specific experiment
# # results_df = run_semantic_calibration_experiment(
# #     dataset_name="CIFAR10",
# #     model_type="GB",
# #     random_state=2,
# #     compression_type="semantic",
# #     compression_param="mobilenet"
# # )

2025-02-13 16:48:41,867 - INFO - Processing CIFAR10 with RF, random_state=2, compression=semantic, param=clip
2025-02-13 16:48:41,867 - INFO - Loading original data for model training...
2025-02-13 16:48:41,867 - INFO - Loading dataset: CIFAR10

Running semantic space calibration experiments for CIFAR10

=== Starting Semantic Calibration Experiment ===
Dataset: CIFAR10
Model type: RF
Compression type: semantic, Parameter: clip

2025-02-13 16:48:42,124 - INFO - Combining and splitting data
2025-02-13 16:48:42,434 - INFO - Data normalization completed
2025-02-13 16:48:42,443 - INFO - Reshaping data for RF model...

Data shapes after loading:
X_train: (36000, 32, 32, 3)
X_val: (12000, 32, 32, 3)
X_test: (12000, 32, 32, 3)

2025-02-13 16:48:42,681 - INFO - Training RF model...
2025-02-13 16:48:42,681 - INFO - Loading pre-trained RF model from output/CIFAR10/2/saved_models\RF_model.keras.
2025-02-13 16:48:42,987 - INFO - Getting model predictions...
2025-02-13 16:48:45,413 - INFO -
=== Compression Initialization ===
2025-02-13 16:48:45,413 - INFO - Original compression_types: ['semantic']
2025-02-13 16:48:45,413 - INFO - Original compression_params: ['clip']
2025-02-13 16:48:45,416 - INFO - Final compression_types: ['semantic']
2025-02-13 16:48:45,416 - INFO - Final compression_params: ['clip']
2025-02-13 16:48:45,416 - INFO - Loading CLIP model openai/clip-vit-base-patch32
2025-02-13 16:48:47,219 - INFO - Initialized clip model for semantic compression
2025-02-13 16:48:47,221 - INFO - Initialize Compression with ['semantic'] and ['clip']
2025-02-13 16:48:47,221 - INFO - Running faiss_exact calibration with semantic compression...
2025-02-13 16:48:47,223 - INFO - Initializing StabilitySpace with faiss library and cosine metric.
2025-02-13 16:48:47,225 - INFO - Applying compression to training data.
2025-02-13 16:48:47,225 - INFO - Input data shape: (36000, 32, 32, 3), dtype: float32
2025-02-13 16:48:47,225 - INFO - Input dimensionality check:
2025-02-13 16:48:47,225 - INFO - - Number of dimensions: 4
2025-02-13 16:48:47,227 - INFO -
=== Compression Call ===
2025-02-13 16:48:47,227 - INFO - Input X_train shape: (36000, 32, 32, 3)
2025-02-13 16:48:47,227 - INFO - Input dtype: float32
2025-02-13 16:48:47,227 - INFO - Train mode: True
2025-02-13 16:48:47,229 - INFO - Detected 4D input: batch=36000, height=32, width=32, channels=3
2025-02-13 16:48:47,229 - INFO - Keeping multi-channel images in 4D. Shape remains: (36000, 32, 32, 3)
2025-02-13 16:48:47,229 - INFO -
Applying semantic compression with parameter clip
2025-02-13 16:48:47,229 - INFO - Before compression shape: (36000, 32, 32, 3)

=== Starting faiss_exact calibration ===
Configuration: {'library': 'faiss', 'mode': 'exact'}

Processing with clip:   3%|▎         | 37/1125 [00:51<25:00,  1.38s/it]

KeyboardInterrupt: